### ISSUE TITLE
Mobile enabled

### ISSUE THREAD

**Issue by g00glen00b** [angular-ui-tree/angular-ui-tree#10]
Can you make it work on mobile devices? When I tried it on my mobile device, it didn't work as expected. The drag is initiated (you can see the placeholder), but the draggable object will not move.

I reproduced the same error on your examples by emulating a mobile device (using Google Chrome). I suppose it has to do with the "mousemove" event that is not executed, but I'm not sure.

**Comment by nikhiljsh22** [comment]
hi,
can you bind touchcancel also with dragEnd, we are having issue, once it is dragged in IPad the dragged element is getting duplicated,means older node isn't getting deleted at dragEnd.
