### ISSUE TITLE
ngRepeat:dupes error after model modified externally

### ISSUE THREAD

**Issue by jrencz** [angular-ui-tree/angular-ui-tree#101]
In case of modifying the tree model from outside of the ui-tree directive (for example with other directive which shares the model or with a controller function) strange thin happens: the model gets modified but after the next attempt to interact with the tree using drag&drop interface one get an error:

```
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.16/ngRepeat/dupes?p0=item%20in%20list&p1=object%3A009
```

I prepared an example based on the demo:
http://plnkr.co/DM2Dfui3PPJ7PgBVtkWP

Notice that after element gets dropped its scope ID gets updated (a new scope is created and data get transferred to it). After modifying the model externally it doesn't.

It is either a bug (if scopes should get updated after model changed) or there should be a convenient way to make the tree reinitialise with the new model.

**Comment by enkodellc** [comment]
FYI there is a fix within new versions of angular "track by $index"
https://docs.angularjs.org/error/ngRepeat/dupes
