### ISSUE TITLE
click on node throw exception of Controller 'uiTree', required by directive 'uiTreeNode', can't be found!

### ISSUE THREAD

**Issue by li-raz** [angular-ui-tree/angular-ui-tree#102]
i wrote a simple tree

 <div ui-tree>
        <ol ui-tree-nodes="" ng-model="treeData" style="list-style-type:none">
            <li ng-init="collapsed = false" ng-repeat="node in treeData" ui-tree-node>
                <span ng-include nv-src="page/pageGroupTemplate"></span>
            </li>
        </ol>
    </div>

template:

<div class="tree-node tree-node-content" ng-show="node.show">
    <a ng-if="node.type === 'SensorGroup'" class="btn btn-success btn-xs glyphicon" data-nodrag ng-click="toggle(this)"
       ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed, 'angular-ui-tree-hidden' : !node.children || node.children.length === 0}"></a>
    <span ng-click="onSelect(node)">{{node.text}}</span>
</div>
<div ng-if="node.type === 'SensorGroup'">
    <ol ui-tree-nodes=" " ng-model="node.children" ng-if="!collapsed" style="list-style-type:none">
        <li ng-init="collapsed = false" ng-repeat="node in node.children" ui-tree-node>
            <span ng-include nv-src="page/pageGroupTemplate"></span>
        </li>
    </ol>
</div>

this tree is "hosted" in a popup div - when i select a node the whole tree disappears and then shown in other location and i get this exception

**Comment by Voles** [comment]
Please create a JSFiddle using latest release (v2.3.0) explaining the issue so we can further investigate.
