### ISSUE TITLE
Collapse Question/Issues

### ISSUE THREAD

**Issue by JLiscom** [angular-ui-tree/angular-ui-tree#111]
Hello,
In my use case, I need the tree to be rendered initially collapsed?
Do you have a way to support this?

Also,
If a item is collapsed it wont allow you to drag items in to it.
This would be a nice feature to have as it would allow dragging in values no matter the state of the item.

I was able to reproduce this in your demo with Firefox 28.

Great work so far.
Thank you,
F().X

**Comment by celestinoramalho** [comment]
Using data-collapsed on the ui-tree element does nothing for me (using 2.1.5).
When i use it on the ui-tree-node elements it works fine, but raises a new problem, i can't create new depths on items with no nodes. All items with no depending nodes at the beggining can´t get a new child node.
Anyone having the same issue?

**Comment by huizhoujava** [comment]
Just add collapsed="true" on the ui-tree-node element.

**Comment by laysveloso** [comment]
Not working for me. I'm using the 2.2.0 version

**Comment by sheymann** [comment]
Not working for me. I'm using the 2.1.4 version

**Comment by adeiji** [comment]
Not working for me either.

**Comment by ernestopye** [comment]
Not working for me either. On 2.1.5 at the moment.

**Comment by FoxUSA** [comment]
@adeiji @ernestopye,
I have it working on my project

Look at these partials
https://github.com/FoxUSA/OpenNote/blob/master/OpenNote/openNote/partials/listPartial.html
https://github.com/FoxUSA/OpenNote/blob/master/OpenNote/openNote/partials/treePartial.html
https://github.com/FoxUSA/OpenNote/blob/master/OpenNote/openNote/controllers/listController.js#L50

**Comment by ernestopye** [comment]
I got this to work, but there's a weird side effect now where I can't drag nodes up the hierarchy, or turn them into a child of their closest sibling by dragging to the right. Has anybody ran into this?

**Comment by burakkilic** [comment]
+1

**Comment by ChavXO** [comment]
+1

**Comment by tcphuis** [comment]
> In my use case, I need the tree to be rendered initially collapsed?
Do you have a way to support this?

angular-ui-tree.js
