### ISSUE TITLE
Bug when init jQuery before AngularJS

### ISSUE THREAD

**Issue by KirillArtemenko** [angular-ui-tree/angular-ui-tree#112]
When adding a script tag of AngularJS before jQuery script tag all works fine. But if add jQuery script tag first drag-and-drop event dont get a .pageX / .pageY parameters :( And nesting not works

jQuery 1.11.0
AngularJS 1.2.15

**Comment by Voles** [comment]
Please create a JSFiddle using latest release (v2.3.0) explaining the issue so we can further investigate.
