### ISSUE TITLE
Inconsistent behavior with ng-repeats using "track by $index"

### ISSUE THREAD

**Issue by amunro** [angular-ui-tree/angular-ui-tree#127]
Hi there,

I've run into an issue relating to the construction of my lists. In my application I need to utilize ```track by``` (specifically ```track by $index```) in my ng-repeats.

Results of the sort can be inconsistent and incorrect when the items listed were generated by ng-repeat utilizing "track by"

When a user sorts position 3 to position 1, the result will be position 2.
Position 4 to position 1 will result in the final position being 4.

This applies to all items root level and nested.

It's hard to nail down an exact case to reproduce, however, repeated sorting of multiple items eventually ends up more and more inconsistent as the steps increase.

I've updated ```demos/group.html``` in the fork below:
beaec5a572fde6b96c3bff78897372dd41ff2272

Thanks!

**Comment by jakehova** [comment]
I too am having this issue with inconsistent drag and drop behavior when using track by.  Performing the conditional via ng-if that uriklar suggested seems to work though.  Maybe, since ng-if creates a new scope for the element, that will help point in the right direction with regards to resolving the bug.

In any case, I switched to one time data binding and removed the track by to improve performance and handle the issue in my particular case, but this is obviously not a long term solution.

**Comment by Voles** [comment]
Please create a JSFiddle using latest release (v2.3.0) explaining the issue so we can further investigate.

**Comment by coryasilva** [comment]
@Voles I think this issue should be re-opened.  [In this Plunker example](https://plnkr.co/edit/lbrDx2L3VZskJ8BTql6s?p=preview) I get an incorrect index on `event.dest.index` of the `beforeDrop` callback.

**Comment by Voles** [comment]
@coryasilva I've dragged the first item just before the last item and te result was `Source Index: 0 Dest Index: 3`. The result should have been `Source Index: 0 Dest Index: 2`.

I will need to further investigate why this happens. Are you able to help with this?

**Comment by coryasilva** [comment]
Yeah let me take a deeper look at the source.  I will respond to this thread with any questions I may have.  Does that sound okay?

**Comment by Voles** [comment]
@coryasilva perfect, thanks in advance! Extra hands are always welcome :smiley:

**Comment by coryasilva** [comment]
Okay I tracked the problem down to [this block of code](https://github.com/angular-ui-tree/angular-ui-tree/blob/ef449bb68164f12147d7268e1546413892857274/source/controllers/nodesCtrl.js#L79-L87).  When using `track by` the `$$hashKey` property does not get set by `ng-repeat`.  Perhaps we can parse out or access the `track by` expression from the [ng-repeat controller](https://github.com/angular/angular.js/blob/v1.4.9/src/ng/directive/ngRepeat.js#L349-L389) and then consume it. Or... be lazy and just pass in an attribute.

**Comment by bronielsen** [comment]
Confirming that I have the same problem using v2.13.0 and v2.15.0

**Comment by ady-ghe** [comment]
still have this issue in 2017!

**Comment by Augus** [comment]
still have this issue in 2017!
Can't using `track by obj.id` too.
