### ISSUE TITLE
Question - animation?

### ISSUE THREAD

**Issue by nickbouton** [angular-ui-tree/angular-ui-tree#134]
Hi @JimLiu, thanks for an excellent module.

I am in the process of switching over from angular-tree-control as it's not quite as full-featured as your control is.

I was wondering, is there any way to insert animations (i.e. slide-toggle type effects) when expanding and collapsing tree nodes, potentially using something like **ngAnimate** (http://www.nganimate.org/)? Have you investigated this at all? From a UX standpoint it would be a nice feature.

Cheers,
-nick

**Comment by RichardJECooke** [comment]
Nick, did you ever get this to work?  I tried adding a simple fade animation for ngHide and ngShow but it didn't seem to do anything.
