### ISSUE TITLE
A tree with two different sub types. A node cannot be dropped into empty node

### ISSUE THREAD

**Issue by searope** [angular-ui-tree/angular-ui-tree#139]
I have an example (http://plnkr.co/edit/u3JiQHSfBJyTnCfqGauK?p=preview) where I have a tree with two different types (folder and file). In the code I'm implementing 'accept' to allow dropping items only to appropriate targets.
First folder "folder0" is empty. And I cannot drag and drop any other folder into it.
If a folder has subfolders then dropping works fine.

**Comment by Voles** [comment]
@searope is this issue still valid?
