### ISSUE TITLE
How to change a property value of dropped element in connected list?

### ISSUE THREAD

**Issue by ankurngm** [angular-ui-tree/angular-ui-tree#141]
Hi,

I am working with Connected list sample at - http://jimliu.github.io/angular-ui-tree/trees.html

When an item is dropped from one list to another, I need to update "title" property of the dropped element by appending value from some variable.

How can I accomplish it?

**Comment by icfantv** [comment]
Just for posterity and anyone else looking, the droppedInto event no longer exists - it was in the code base at one point.  If you need the receiving tree to fire an event when an item is dropped, I'm still looking for a solution but right now I think we're screwed.

**Comment by charlie-wasp** [comment]
@icfantv I know, it's been a long time, but now I am struggling with the same problem, did you find (and remember) some solution?

**Comment by ankurngm** [comment]
Thou, I don't use this control anymore, but I believe, I implemented AngularJs Watch for custom processing. Here is the link that might help you get started - http://tutorials.jenkov.com/angularjs/watch-digest-apply.html

**Comment by icfantv** [comment]
@charlie-wasp, I might be able to see what I did.  I don't work there anymore so I'll need to reach out to colleagues.  I'm in meetings all day so it might be tomorrow.  Cool?

**Comment by charlie-wasp** [comment]
Yes, of course! Thank you!
