### ISSUE TITLE
Limit drag and drop to sibling-level only

### ISSUE THREAD

**Issue by sam-keen** [angular-ui-tree/angular-ui-tree#144]
Hi there, 

I'd like to limit the drag and drop capability to only sibling-level elements. To give the tree example, I'd like to be able to reorder node2.1 with node2.2, but I do not want to be able to move them outside of the boundaries of being children of node2. Equally, I'd like to be able to reorder siblings like node1 and node2, but I want to limit them so that they cannot become child nodes. Is this sort of limitation possible? Thank you in advance!

**Comment by BKB503** [comment]
any one has working example?
