### ISSUE TITLE
destIndex for accept() function not returning correct result sometimes

### ISSUE THREAD

**Issue by egervari** [angular-ui-tree/angular-ui-tree#146]
Hello,

First, thanks so much for this little library. It's really helpful. 

I'm currently working on a project that has a screen where you can edit a nested view of sections and pages that exist in those sections. It's similar to Windows Explorer, where you have folders and files. The functionality is nearly identical.

Of course, this example is a bit more complicated compared to where you have all of the nodes as the same type. The logic to check whether a section or page can be nested is a bit more complicated, so we really need accept() to have a lot of code to make all of the correct decisions about whether a node can be dropped or not.

I have nearly finished all of the conditions that need to be checked, and it's working almost perfectly. However, there is one case where I think I stumbled upon a bug in the library itself. 

In my application, sections and pages can be siblings of the same node, just as folders and files can be siblings in Windows Explorer. I'd really like to enforce the rule that sections should always be placed before pages, so accept() should return false when the previous sibling to destIndex is not a section. Unfortunately, whenever I place a source node into a destination node where the destination should 1, the accept() function passes 0 into destIndex instead. This causes my custom code in accept() to incorrectly inspect the wrong sibling (which is destIndex = 0), and this causes accept() to return true when it should have returned false. Here is what happens visually:

![bug](https://cloud.githubusercontent.com/assets/442792/3111084/2fb8b94e-e6ad-11e3-8145-8c6c5cac3efa.png)

This is the oddest bug because the accept() function will return the correct result when the destination index is 2 or higher. My guess is that when destIndex is 2, your library may return 1 or 2... which in either case causes my code to return false. However, I feel like destIndex is probably being incorrectly set.

When inspecting destIndex in the browser's console, it's a bit hard to track because it updates 9 times very rapidly upon dragging.

I have managed to get accept() to pass 1 for destIndex sometimes, but it requires the user to drag onwards to destIndex 2 and then back again. Either way, it still lets me place my source node into a position that is incorrect because destIndex will ultimately return 0 when it should have returned 1.

I understand the logic I need to write in the accept() function to make this work, but I really do fear that destIndex is not being reported correctly. This is what I had in my mind:

```
            var previousSibling = destNodesScope.$modelValue[destIndex - 1];
            if(destIndex > 0 && previousSibling && previousSibling.type === 'PAGE') {
                return false;
            }
```

This is a breaking problem for my application. Is there any way we can work together to get a fix?

Thanks.

**Comment by nikolaygit** [comment]
@konstardiy thank you for noting that the correct destIndex is in ``eventData.dest.index`` of the ``dropped`` event! This helps me futher, because in the accept event the destIndex is not always correct (version 2.4.0)!
