### ISSUE TITLE
看作者似乎是中国兄弟，不知用中文提问是否可行，问个大数据量节点数时的性能优化的问题。

### ISSUE THREAD

**Issue by Twobuger** [angular-ui-tree/angular-ui-tree#148]
我使用ui-tree这个指令处理树，总节点数如果在几百条以内，没什么问题，但如果节点数达到了1000这个级别，在IE浏览器里基本属于无法使用的状态（Chrome还好），如果这些节点实际分布比较分散，有大量的树枝节点，每层树枝子节点能控制到1、200条，这时还可以利用 ng-if指令 + 默认折叠 子节点的方式将整个树的加载时间分散开。

如下面这个模板的写法

<ol ui-tree-nodes  ng-model="node.nodes" ng-class="{hidden: collapsed}" ng-if="!collapsed">
            <li ng-repeat="node in node.nodes"   ui-tree-node data-collapsed="true"  ng-include="'nodes_renderer.html'" ng-show="visible(node)">
            </li>
          </ol>

但现在我遇到了更棘手的问题，有些个别的树枝节点，子节点数已经超过1000了，这时展开此节点就会卡死相当长时间，并且由于我用了ng-if来控制实际输出，在收缩节点后再次展开还会花相同长的时间，如果不使用ng-if，那么第一次加载树的时间就更长了。

我的想法是能在每层节点上提供分页和筛选功能，但不知如何下手，还请指教。

**Comment by HelloAmy** [comment]
我也遇到这个问题了，我的数据量是3千多条，需要增删改，每次渲染浏览器非常慢...
