### ISSUE TITLE
[Chrome Browser] drag-n-drop is broken

### ISSUE THREAD

**Issue by iamruss** [angular-ui-tree/angular-ui-tree#154]
Here is the [demo which uses the same code and markup](http://plnkr.co/edit/RTu9KLwMfi6COSye1RPv?p=preview) as official http://jimliu.github.io/angular-ui-tree/tree.html

The only difference is that it uses the latest ui.tree code v2.1.4, while the official example uses 2.0.13.

It only works if you have this setup:

1) have browser window with the tree
2) have another browser window on top of it with whatever site loaded in it, overlapping the window with the tree
3) make sure the browser window has focus (click on it) - move mouse over to the window with the tree and try dragging - it will work

Here is the animaged gif, demoing the behaviour:
![ui tree](https://cloud.githubusercontent.com/assets/204439/3206774/c0c787f4-edcd-11e3-86a2-a191e0ea7c3e.gif)

In the Plunker example  source code, feel free to uncomment v2.0.13 and it will work

**Comment by ex37** [comment]
If anyone is still interested, just use ``nodrag`` attribute, instead of ``data-nodrag``

**Comment by gregwym** [comment]
Hi @ex37, thanks for the note! I will give a try and update here.

**Comment by iamruss** [comment]
Thanks *ex37*, looks like it works.

**Comment by gregwym** [comment]
Hi @ex37, 

I just tried to use `nodrag` instead of `data-nodrag` but no luck. Apparently, angular-ui-tree does not recognize `nodrag` attribute. 

Please see https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/services/helper.js#L56. It only check for specific `data-nodrag` attribute.

**Comment by Voles** [comment]
@gregwym does this issue still occur using v2.3.0?

**Comment by gregwym** [comment]
Hi @Voles , 

I haven't try v2.3.0 yet, but v2.2.0 was causing some backward compatibility issues. For example, some block that were not draggable became draggable. So I reverted the upgrade. 

I will give v2.3.0 a try and dig more into issues this time. 

Thanks, 
Greg

**Comment by Voles** [comment]
v2.2.0 has been reverted by @JimLiu because there were too many issues. Looking forward to hear about your findings with v2.3.0.

**Comment by ericmchan** [comment]
Upgrading to v2.4.0 appears to have fixed the problem on Windows with Chrome for us! We haven't observed this issue since the upgrade. (@gregwym has moved onto a different role at another company, and I've taken over his work on our project.)

**Comment by gregwym** [comment]
@ericmchan Awesome!!!!!!!

**Comment by iamruss** [comment]
Just tried the example I used initially with the code from latest commit and I can confirm everything is fine now. Thanks.

**Comment by Voles** [comment]
@ericmchan thanks for testing!
