### ISSUE TITLE
Accessibility options

### ISSUE THREAD

**Issue by subvertnormality** [angular-ui-tree/angular-ui-tree#155]
Hi there, first of all excellent work on this component - it is very flexible.

I was wondering if there was a way to add alternative ways to move nodes (around in the same list or to other lists) by other means than drag drop. Specifically i think it is important to offer alternatives such as keyboard shortcuts and/or links to perform a movements for users that are not able to drag and drop. 

Is there a way to hook in to add these shortcuts/alternate controls?

Thanks again

**Comment by Voles** [comment]
@clementprevot / @subvertnormality any updates on this?

**Comment by subvertnormality** [comment]
No updates, we came up with a manual solution to move nodes around by manipulating the objects themselves, if I recall correctly. It was a while ago now though, I'm afraid.
