### ISSUE TITLE
Browser window doesn't scroll when dragging beyond visible area on Win7 in IE9,10,11

### ISSUE THREAD

**Issue by kburnell** [angular-ui-tree/angular-ui-tree#158]
Browser window doesn't scroll when dragging beyond visible area on Win7 in IE9,10,11.  It works in Windows 8/8.1 on IE 9,10,11 and works in other browsers but doesn't seem to work in Win7 on IE9,10,11.

**Comment by Voles** [comment]
@kburnell if this issue is still valid can you please create a JSFiddle using the latest release (v2.3.0) explaining the issue?

**Comment by AndrewIsh** [comment]
This appears to be a duplicate of #544. I am experiencing the same problem and have created [a plunker](https://github.com/angular-ui-tree/angular-ui-tree/issues/158) to demonstrate. Is there any chance someone could take a look at this as it's quite a problem for IE users with big trees! Thanks :)

**Comment by jacobscarter** [comment]
Available in v2.21.1
