### ISSUE TITLE
drop target outside of tree

### ISSUE THREAD

**Issue by chino23** [angular-ui-tree/angular-ui-tree#166]
Thanks again for this awesome library. It's just great.

I am trying to implement as setup where I have a category list on the left, and on the right side a ui-tree is showing the nested tasks for the selected category.

What I need is a possibility to drag single tasks onto the category item on the left side, to  drop it there and move it to another category. The problem is, the category list is not a ui-tree list, just a normal ui-sortable. 

Is it possible to somehow define drop targets outside of an ui-tree?

**Comment by amanguptaDeveloper** [comment]
How can i drop outside the ui tree. I no longer need a node and want to remove it from the tree by dragging and droping outside. Is this possible ?
