### ISSUE TITLE
Connected tree with the same scope

### ISSUE THREAD

**Issue by marcelorl** [angular-ui-tree/angular-ui-tree#171]
Hey, 
I would like to know if it is possible to have a connected tree using the same scope, instead of multiple scopes. 

I have already created this solution, but it is all done in javascript and it was like, a huuuge work. I tried to use the same scope for multiple tables but it is getting the index from the table, the idea was, get the index from the scope.

The purpose of this is, send just one json response to the server, instead of multiple jsons.

Do you think that is possible?
If you think that is possible, could you please at least give me some ideas how can I change the directive to make it work?

 Actually it is just a suggestion. You did a very cool work. Congratulations.

**Comment by Voles** [comment]
@marcelorl any luck using the latest release (v2.3.0)? Do you still need this?
