### ISSUE TITLE
[$compile:ctreq] Controller 'uiTree', required by directive 'uiTreeNodes', can't be found!

### ISSUE THREAD

**Issue by Tanax** [angular-ui-tree/angular-ui-tree#175]
I've seen this error in your issues-list before but those errors does not seem to be triggered the same way mine is.

Basically, I have a list of nodes. My HTML looks like this:

nodeTree.html:

``` html
<div ui-tree="treeOptions" data-drag-delay="100" data-empty-place-holder-enabled="true">
    <div ui-tree-nodes="" ng-model="nodes">
        <div ng-repeat="node in nodes" ui-tree-node ng-include="'templates/nodeTreeItem.html'"></div>
    </div>
</div>
```

nodeTreeItem.html:

``` html
<div ui-tree-handle ng-class="node.type" selectable="qStructure">
    <span class="type">{{ node.type | limitTo:1 }}</span> - <span class="node-label">{{ node.label }}</span>
</div>
<div ui-tree-nodes="" ng-model="node.nodes">
    <div ng-repeat="node in node.nodes" ui-tree-node ng-include="'templates/nodeTreeItem.html'"></div>
</div>
```

I have a "readOnly" mode in my application and have just added a "live-updates" to it so that whenever someone else does some edit in the application, those in "readOnly" will automatically get those updates. In order to do so, I replace the $scope.nodes with a new list of nodes fetched from the database, like so:

``` javascript
DocumentService.get({'id': $scope.documentId}).$promise.then(function (result) {
    $scope.nodes = result.nodes;
});
```

When that happens, this error is triggered. Is there some re-compiling I need to do or something? I've tried $digest and $apply but they trigger additional errors saying that a digest is already performing.

Does your plugin lose the reference when replacing the node-list like that?

**Comment by ImportSumit** [comment]
Hi Jim ,
I am getting same error  Error: [$compile:ctreq] Controller 'uiTreeNodes', required by directive 'uiTreeNode', can't be found! because I am using ng-tree for creating a specific tree structure 

<div ui-tree >
<ul ng-tree="testData"  ui-tree-nodes ng-model="testData">
    <li ui-tree-node >
    <div ui-tree-handle>
    <span id ="{{item.id}}">{{item.description}}</span>
    </div>
    </li>
</ul>
</div>
can you help me out
