### ISSUE TITLE
Nested tree nodes, empty array issues

### ISSUE THREAD

**Issue by ishmaelthedestroyer** [angular-ui-tree/angular-ui-tree#177]
When creating a nested tree node (a series of nodes associated with a tree within another series of nodes associated with a tree), a few issues arise.

The main issue issue is that once all the nodes have been moved off of a particular group inside the nested tree, the model fails to update and display the placeholder.

Example:

Here's a 3 column grid I setup with just a single tree. Everything seems to work fine, as in the panels can be moved across columns and groups:
http://jsfiddle.net/6BtNj/1/

It breaks when the outer group is also specified as a sortable array, shown here. You can move the outer panels, i.e. "group one" and "group two", and you can move the inner items across the top column, but as you'll see, the empty lists don't have placeholders.
http://jsfiddle.net/6BtNj/

Any help?

**Comment by none-da** [comment]
> The ui-tree can't be nested.

@JimLiu The `ui-tree` still cant be nested ? If not, is there a way to make it work with nested trees ?

**Comment by brandonreid** [comment]
+1 for a way to have an empty placeholder in `ui-tree-nodes`

**Comment by area** [comment]
+1

**Comment by aerypton** [comment]
+1
