### ISSUE TITLE
Give us a like on ngmodules

### ISSUE THREAD

**Issue by JimLiu** [angular-ui-tree/angular-ui-tree#18]
If you are using it and like it, please [Give us a like on ngmodules](http://ngmodules.org/modules/angular-ui-tree)

Thanks

**Comment by Voles** [comment]
Thanks all :+1:

**Comment by chino23** [comment]
@Voles do you have access to the ngmodules page so we can update it with the current .io site and pointing to the github.com/angular-ui-tree instead of the jim-liu link for consistency?
