### ISSUE TITLE
Problem with orderBy

### ISSUE THREAD

**Issue by anxodio** [angular-ui-tree/angular-ui-tree#181]
```
<div ui-tree="treeUserOptions">
    <ol ui-tree-nodes ng-model="rel.users" data-nodrop>
         <li ng-repeat="item in rel.users | orderBy:'id'" ui-tree-node ng-include="'relUserRenderer.html'"></li>
    </ol>
 </div>
```

When you fill a tree with ngrepeat and orderBy, if you drag and drop an item, it fails and drop the item that was in the source position without orderBy applied.

It's possible? Or is my fault?

**Comment by brianfeister** [comment]
@clementprevot - In my case I'm not using drag/drop but I still am unable to use a custom `orderBy`. Is this a known limitation? Anything that could be done to fix it?

**Comment by shayanea** [comment]
Use filter in your controller to sort data 
$scope.TreeObject = $filter('orderBy')(data, 'Sort');
