### ISSUE TITLE
Is item can be edit?

### ISSUE THREAD

**Issue by yolo2013** [angular-ui-tree/angular-ui-tree#182]
As you see, dragable is cool.But is this tree's node can be edit? Should i make it editable with add attribute contentEditable?

**Comment by biclon** [comment]
If the example mentioned in the previous post doesn't work for you then take a look at integrating the x editable directive and using the onshow and onaftersave callback methods. This is what I ended up using and it worked well for me. 

Here's a link that might help you http://vitalets.github.io/angular-xeditable/#ref-element

**Comment by yuvraj11** [comment]
Is edit node name functionality part of this component yet? If not, how can I implement it on my own? Is it as simple as - `<a href="#" editable-text="user.name" [attributes]> {{user.name | "empty"}} </a>`
