### ISSUE TITLE
Cannot read property 'exp' of undefined

### ISSUE THREAD

**Issue by dichiohare** [angular-ui-tree/angular-ui-tree#185]
Hi,

I've come across the following issue in the image below. There must be something that i'm missing but I can't put my finger on it.

![image](https://cloud.githubusercontent.com/assets/8290025/3721327/572dd9dc-165f-11e4-89bb-6741acce869a.png)

I have the following scripts included:
       jquery-2.1.1.js
       angular.js (v1.2.20)
       bootstrap.js (v3.1.1)
       angular-ui-tree.js

The controller and html code is pretty much the same as in the connected trees demo.

Thank you.

**Comment by Voles** [comment]
@MagicIndustries are you up to create a PR for this?

**Comment by kadosh1000** [comment]
Just happened to me too, disabling batarnag did the job

**Comment by MarkisLt** [comment]
AngularJS v1.4.4
Angular UI Tree v2.8.0

Disabling Batarang helped.

**Comment by JLLeitschuh** [comment]
+1 for disabling batarang

**Comment by BlakeBrown** [comment]
Made a pull request #664 to fix this issue in the latest version

**Comment by Vixxd** [comment]
Hi all,

I'm still getting this issue without batarang. I have the map included on a single page:

```
        <ui-gmap-google-map center='map.center' zoom='map.zoom'>
            <ui-gmap-marker coords="marker.coords" idkey="marker.id">
            </ui-gmap-marker>
        </ui-gmap-google-map>
```

 and the following code to init:
```

    if (site.status) {
      $scope.error = ... etc.
    } else {
      getMapData();
      ...
    }

    var getMapData = function () {
      //Get map data
      $scope.map = {
        center: {
          latitude: $scope.site.location.x,
          longitude: $scope.site.location.y
        },
        zoom: 5
      };

      //Get marker to display on map
      $scope.marker = {
        id: 0,
        coords: {
          latitude: $scope.site.location.x,
          longitude: $scope.site.location.y
        }
      };
    };
```


The error is as follows:
```
angular.js:13424 TypeError: Cannot read property 'exp' of undefined
    at setIfChange (angular-google-maps.js:1900)
    at Scope.$digest (angular.js:16869)
    at angular.js:17064
    at completeOutstandingRequest (angular.js:5824)
    at angular.js:6100
```

Versions:
```
    "angular": "^1.4.0",
    "angular-google-maps": "~2.2.1",
```
Any help would be appreciated.

**Comment by nordoff** [comment]
@Vixxd Try upgrading to 2.3.3. Moving from 2.0.11 to 2.3.3 fixed a `Cannot read property 'exp' of undefined"` for me

**Comment by archasek** [comment]
@nordoff how did you upgrade it?

**Comment by nordoff** [comment]
I am using bower, so I simply changed the version in dependency list in my bower.js

**Comment by archasek** [comment]
I did it too but IMHO it doesn't work as the most recent version is 2.15.0 O_o

Could you please give me the exact bower.json line?

**Comment by nordoff** [comment]
@archasek 
"angular": "^1.5.2",
"angular-google-maps": "2.3.3",

Hope that helps

**Comment by ladmerc** [comment]
+1. Same issue using uib-typeahead.

Disabling batarang works, but that's not ideal

**Comment by yasoCH** [comment]
thanks! had the same error but with angular inspector, which is based on batarang
