### ISSUE TITLE
Drag and drop in big trees takes a long time to initialize

### ISSUE THREAD

**Issue by mdenburger** [angular-ui-tree/angular-ui-tree#186]
With big trees (i.e. with more than 500 nested items) drag and drop does not work. Strange enough, it seems to start working after just waiting for a long time.

For example, I generated a 3-level deep tree in which each item has 8 children. That tree contains 8^3 = 512 items in total. Drag and drop in such a tree does not work after the demo page has loaded. Dragging the top-most item simply freezes the dragged handle. Yet after waiting for about 10 seconds, drag and drop becomes responsive again. I tested this in Chrome 36.0.1985.125 on Ubuntu 13.10.

The issue becomes even more noticeable when the model of each item gets a 'collapsed' boolean that is passed to the ui-tree-node directive with

```
    data-collapsed="item.collapsed"
```

The bigger the tree, the longer one has to wait before drag and drop becomes responsive. In a tree with 1000 items, it already takes several tens of seconds.

**Comment by sandeepmalviya581** [comment]
there is problem in rendering the tree and take more time and the page get irreponsive it may affect performance issue
