### ISSUE TITLE
Drag&drop really slow with a big tree

### ISSUE THREAD

**Issue by Darkein** [angular-ui-tree/angular-ui-tree#188]
Hi,

With a really big model (~1000 childrens on ~10 levels), the drag and the drop are really slow, even if i just drop a tree with one level on the same place without moving it vertically.

When i profiling drag and drop with Chrome timeline, this warning appear often: "Forced synchronous layout is a possible performance bottleneck.". Maybe you can cache some layout calculations like element[0].getBoundingClientRect or $document[0].body.scrollTop to speed up the drag?

At the drop, my impression is that each element of the tree is redrawn, it may be possible to cache the children of the parent node?

For information, i have an intel xeon W3530 CPU with 12go of ram, I am afraid the result is worse on a less powerful computer :(

Thanks for your job, it's really useful.

**Comment by Voles** [comment]
@Darkein as this issue is rather old I suggest to create a JSFiddle using the latest release (v2.3.0) and create a new issue if this still occurs.

**Comment by Voles** [comment]
@bdauton feel free to create a JSFiddle using the latest release (v2.3.0) and create a new issue if this still occurs.

**Comment by Darkein** [comment]
I don't have the problem anymore with the latest version. With ng-if="!collapsed" collapsed="true" on each ui-tree-node (and not ui-tree-nodes), it's faster than ever.

Thanks!
