### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Rodeoclash** [angular-ui-tree/angular-ui-tree#199]
I'll admit I'm not an expert on this but I think their might be a memory leak with the keyBinding code:

```
 angular.element($window.document.body).bind("keydown", function(e) {
              if (e.keyCode == 27) {
                scope.$$apply = false;
                dragEnd(e);
              }
            });
```

I don't think this is getting unbound when the directive is destroyed.

**Comment by Voles** [comment]
@NickPadilla, @Rodeoclash this issue has been fixed here https://github.com/angular-ui-tree/angular-ui-tree/commit/9ef029906d4ac5482ea07d98a0f2a5bd8bba5f6c
