### ISSUE TITLE
Toggle/remove not firing?

### ISSUE THREAD

**Issue by stianl** [angular-ui-tree/angular-ui-tree#200]
When clicking the expand/collapse buttons on the [demo page](http://jimliu.github.io/angular-ui-tree/) the toggle and remove functions referenced by `ng-click` never seems to be triggered? The items are collapsed/expanded, but if I put a breakpoint at `scope.toggle()` the debugger never stops there. The `newSubItem` function seems to be called if I click the plus sign however.

**Comment by idmanish** [comment]
I am also facing same issue on my code, is there any specific solution
toggle  function referenced by ng-click never seems to be triggered?

When I put one more div in my html and put  ng-clcik it works fine
But div with ui-tree and its child have this issue

**Comment by nglasantha** [comment]
remove track by $index
