### ISSUE TITLE
console error when first opening, but no loss in functionality?

### ISSUE THREAD

**Issue by chino23** [angular-ui-tree/angular-ui-tree#201]
I've got a weird error.

I have a view which has a ui-tree, and when I load it for the first time, and it has data in it, I get a few errors in the console, like

```
 Error: [$compile:ctreq] Controller 'uiTree', required by directive 'uiTreeNodes', can't be found!
 Error: [$compile:ctreq] Controller 'uiTreeNodes', required by directive 'ngInclude', can't be found!
```
The thing is, it still works, everything.

When I move away to another view, and come back later, it doesn't say that anymore. Only the very first time it fires up. But the data in the controller gets loaded every time anew, so I don't really understand what's going on.

The code in the view is 
```
<div ui-tree="taskList" data-max-depth="3" id="tree-root">
    <ol ui-tree-nodes="" ng-model="tasks[category._id]">
        <li ng-repeat="node in tasks[category._id]" ui-tree-node ng-include="'templates/task-template.html'"></li>
    </ol>
</div>
```

and the template has

```
<ol ui-tree-nodes="" ng-model="node.nodes" ng-class="{hidden: collapsed}">
    <li ng-repeat="node in node.nodes" ui-tree-node ng-include="'templates/task-template.html'">
    </li>
</ol>
```

**Comment by clai1018** [comment]
Getting this bug as well. Has there been any update?

**Comment by hstarorg** [comment]
How to solve it?It's a problem for me.

**Comment by chino23** [comment]
I managed to get a workaround for this. The problem seems to occur when the array of the ng-repeat has not been initialized yet. 

So if the ng-repeat loops over an array 'data', it helps to put in the controller init code 

    $scope.data = [];

The problem comes up when the $scope.data has not been set yet. Just putting an empty array fixes this for me.

**Comment by Voles** [comment]
Can't reproduce this error with the latest release (v2.3.0). Please create a JSFiddle explaining the issue so we can further investigate.
