### ISSUE TITLE
Can't drop a node into other node which has no child items

### ISSUE THREAD

**Issue by pssblues** [angular-ui-tree/angular-ui-tree#203]
First, thanks for this great directive!

I have a recursive tree view layout.
Some node has multiple child nodes, and some does not.

So, If I try to drag a node onto another node which has no child nodes, I can't see the drop target animation.

Any nice or hack way to do this?

Thanks

**Comment by nikolaygit** [comment]
thank you @labibismaiel, setting the children array to [] fixed the issue for me!

**Comment by amurtola** [comment]
I had the same problem.
In my case problem was in ng-if condition before node repeater
e.q.

<ul ng-if="item.MailAddresses.length > 0" ui-tree-nodes="" ng-model="item.MailAddresses">
<li ng-repeat="item in it......"></li>
 </ul>

**Comment by brandonreid** [comment]
Would be great if there was an ability to add an empty node inside of `ui-tree-nodes`, similar to the empty placeholder that shows up when the entire tree is empty. 

I've faced with angular ui router a number of times in different projects.
Say I have something like this:
<img width="230" alt="screen shot 2015-08-24 at 2 24 37 pm" src="https://cloud.githubusercontent.com/assets/6776415/9451447/f2c9862a-4a6b-11e5-9ff7-9f4352e0a126.png">
Sections can not be empty. When there are no questions in a section I show a message that says 'empty', but it's tough to drag questions into an empty section without un-intuitively dragging right. If I could add `ui-tree-nodes-empty-placeholder="true"` (or something more elegantly worded) to `ui-tree-nodes`, I could make a much better experience there.

**Comment by bartrail** [comment]
I also had a similar problem, the tip from @Kaylors helped me figuring out how to fix this. Unfortunately I needed to manually iterate all $childScopes and `uncollapse` them to _enable_ the child list for drag support.

    dragStart : function(event) {
      // uncollapse all empty root nodes to enable dragging into empty parents
      angular.forEach(event.source.nodesScope.childNodes(), function($childScope) {
        if ($childScope.item.children.length == 0) {
          $childScope.collapsed = false;
        }
      });
    },

don't know if this is a good practice or not.. any advices are appreciated. I'm just glad I can add children to empty parents again :)

**Comment by jacksoncharles** [comment]
Throwing my experience into the pot, I had the following configuration

```
    .constant('treeConfig', {
      treeClass: 'angular-ui-tree',
      emptyTreeClass: 'angular-ui-tree-empty',
      hiddenClass: 'angular-ui-tree-hidden',
      nodesClass: 'angular-ui-tree-nodes',
      nodeClass: 'angular-ui-tree-node',
      handleClass: 'angular-ui-tree-handle',
      placeholderClass: 'angular-ui-tree-placeholder',
      dragClass: 'angular-ui-tree-drag',
      dragThreshold: 3,
      levelThreshold: 30,
      defaultCollapsed: true
    });
```

and the culprit was 

`      defaultCollapsed: true`

which I changed to read

`      defaultCollapsed: false`

and everything worked perfectly.

Thanks for the awesome solution, really great.

**Comment by DoobleD** [comment]
Thank you @Kaylors and @jacksoncharles, I had the same problem, this helped a lot !

**Comment by RicardoFazzi** [comment]
Thanks @amurtola your answer helped me a lot !!
