### ISSUE TITLE
How do you detect the Ctrl or Shift key during a drag

### ISSUE THREAD

**Issue by william-poitras** [angular-ui-tree/angular-ui-tree#211]
I want to use Ctrl to indicate a Copy operation when dragging a node.  Is there a way to do this?

**Comment by dayres** [comment]
Is there a way to set this behavior as the default when dragging from one tree to another tree?

**Comment by enkodellc** [comment]
@clementprevot I am not having much luck implementing this. Any chance you have a plunker for example?

I see when I start to drag an element it does an immediate clone. But when I drop that element on the same tree or a different tree then the clone in the original tree is gone. 

I am looking to create an attribute that prevents any remove of the source tree. It only populates another tree with cloned elements. Also the source tree I need the nodrop to work and I am having zero luck accomplishing this. If you could point me in the right direction I would greatly appreciate it.

**Comment by devmca123** [comment]
I am still not able to drag and drop multiple item at a time..could you please help me on this..and If possible please upload a sample code how to use it.

**Comment by AlexDEVpro** [comment]
Has this function been removed? Is it possible to copy the node from one branch to another within the same tree using the latest version?
