### ISSUE TITLE
drag&drop error when "confirm(...)" in beforeDrop callback event

### ISSUE THREAD

**Issue by korj** [angular-ui-tree/angular-ui-tree#213]
In my project I need to confirm node drap&drop before save changes to server. In "beforeDrop" callback I inserted JavaScript confirm("...") and set $$apply correspondingly to user answer. But I encountered with angular error "$apply already in progress". Problem occurs in IE11 and Firefox. Crome is ok, it works differently.
Detailed problem description:
1) drag&drop any node to some other place
2) see the confirmation dialog
3) while mouse is outside of the confirm dialog it's ok, tree waits for user answer. But the moment cursor hovers dialog window, "dragCancelEvent" fires and tries to cancel drop, while we waiting for user answer
4) angular "$apply already in progress" error occurs

In my fork I've commented out line with "onmouseleave" event binding and all works fine. Can you explain was it a bug, or I did something wrong?

options = {
            beforeDrop: function(params) {
                if (!confirm("Are you sure?")) {
                        sourceNode.$$apply = false;
                        return;
                    }
                }

**Comment by bronielsen** [comment]
I made two branches to implement the change I ended up making. Take a look and comment.
bronielsen:bronielsen-patch-confirmationDialog
and
bronielsen:bronielsen-patch-confirmationDialog-1
