### ISSUE TITLE
Stickiness parameters for better sorting

### ISSUE THREAD

**Issue by pastinepolenta** [angular-ui-tree/angular-ui-tree#216]
**Scenario**
Currently I have to drag an item more or less entirely over the previous or next item before seing the placeholder changing position. This means that the items will overlap for a while while dragging. It would be nice to use a parameter to prevent this overlap (as soon as I drag A over B, this B takes the place of A and in place of B I see the placeholder). 

**Ideas**
- a "percentage parameter" called something like "stickiness" that receives an integer

E.g. (consider only the case moving from bottom to top, swap for the opposite case)

stick = 0 the top of the dragged is just right above the bottom of the overlapped
stick = 50 the top of the dragged is 50% above the bottom of the overlapped (50% of the overlapped, meaning right above the middle of the overlapped, so it overlaps for 50%)
stick = 100 the elements shall entirely overlap in order to start the swap

(Of course, it's in the case of the movement to the bottom of the page, just invert the top/bottom when going up)
- this parameter should be a good one, combined with another one that will allow to choose if we want to calculate the overlapping from top or from bottom of the dragged element. Thus, it will be fully customizable.
- One precision about the "middle of the overlapped". If the overlapped element is a parent with children, and that you are on the same level as the parent while dragging your element, then the middle is the middle of the complete tree (parent + children) and the bottom is the bottom of the last child.

**Comment by stilllife00** [comment]
@JimLiu @clementprevot this handy "coverage" parameter is gone after the revert on commit 800dd0a43ce105d6301cd42038c1a28dbe3cd21e
What was the reason to revert ? can we have this feature back ?
