### ISSUE TITLE
How to get child nodes scope from parent scope?

### ISSUE THREAD

**Issue by tehnrd** [angular-ui-tree/angular-ui-tree#224]
I need to be able to access a child scope from a parent scope but I am having a difficult time figuring this out. I read the docs and searched the issues but I'm not making progress. For the sake of this example let's just say we want to get the scope of the first child.

tree-node-content.html

```
<div class="tree-node tree-node-content">
    <!-- pass scope of this node to getFirstChildScope method -->
    <a ng-click="getFirstChildScope(this)">hi</a>
</div>
```

controller.js

```
$scope.getFirstChildScope = function(scope){

    //All of these return undefined
    console.log(scope.$nodes);
    console.log(scope.$childNodesScope.$nodes);
    console.log(scope.$childNodesScope.$modelValue[0].$scope);
    console.log(scope.$childNodesScope.$modelValue[0].$nodeScope);

}
```

All of those methods return `undefined`. Is there any way to access child node scope from a parent scope?

**Comment by tomercagan** [comment]
It's worth noting that the way child nodes appears depends on your bounded variable(s).
For example, in my case I have the following template / data:

    <div class="tree-node-content">
         
    </div>
    <ol ui-tree-nodes="" ng-model="program.childPrograms" class="list-group" ng-class="{hidden: collapsed}">
        <li ng-repeat="program in program.childPrograms" ui-tree-node ng-include="'partials/item-renderers/pages/settings/program-tree-template.html'" ng-show="visible(program)"
        class="list-group-item tree-node">
        </li>
    </ol>

And thus, the child nodes are accessible as `childPrograms` property and not `childNodes`. For example, to search child nodes in my case would work as so:

    function searchChildren(scope) {
        if (scope.childPrograms) {
            for (var i = 0; i < scope.childPrograms.length; i++) {
                if (searchChildren(scope.childPrograms[i])) {
                    return true;
                }
            }
        }
        return false;
    }
