### ISSUE TITLE
Have all nodes collapsed by default?

### ISSUE THREAD

**Issue by johnmckay-reward** [angular-ui-tree/angular-ui-tree#225]
Is it possible to have all nodes collapsed by default, I feel as though combining this with ng-if would speed things up a lot but at the moment I have to load everything and wait for the browser to render all of the nodex before I collapse them, slowing things down.

Maybe I'm missing something obvious? Thanks

**Comment by KaustubhDevasthali** [comment]
Hi,

Using ng-if instead of ng-class insanely imporved performance.

However in my case, I was able to drag the nodes when using ng-class. Now using ng-if, I'm unable to drag any node from the tree. 

Any suggestions??
