### ISSUE TITLE
Accept callback no longer firing

### ISSUE THREAD

**Issue by gilluminate** [angular-ui-tree/angular-ui-tree#230]
It seems that the Accept callback is no longer firing with the latest code. Even a simple console log doesn't get triggered from within Accept.

**Comment by zachlysobey** [comment]
So... did this change back to be in the style of `<div ui-tree="treeOptions">` again?

Following [this stackoverflow answer](http://stackoverflow.com/a/28578027/363701) and this thread, I used the `options=...` style, but that didn't work. Changing it back to `ui-tree=...` did work however, and I see that is the style referenced in the README.

**Comment by Voles** [comment]
The configuration is stored in a constant of the component. So there is no way to change the configuration from outside for now.

A PR's to make the options configurable is welcome!

See https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/main.js
