### ISSUE TITLE
Inconsistent root level item reordering

### ISSUE THREAD

**Issue by brentbaum** [angular-ui-tree/angular-ui-tree#231]
### Inconsistent root level behavior
Item dropping is not consistent on the root level of infinitely nested templates. There are two scenarios where I have experienced problems, with the latest version of angular-ui-tree. Both occur when the user drags a node that was not the last dragged node.

Here's a [Plunker that demonstrates the bugs](http://plnkr.co/edit/UNx7GvaVtftHr47CpG4h?p=preview).

### Moving siblings
1. Create node (101)
2. Create node (102)
3. Move node 102 under 101
4. Move node 101 under 102. This should cause 101 to be placed at index 2 in coll, one index further than it should.

### Adding children to empty sibling
1. Create node (101)
2. Create node (102)
3. Move 102 under 101
4. Move 101 under 102
5. Attempt to add 101 to 102. The page tries to add 101 to itself, as shown by the expanded border around 101. 

The second scenario only occurs when the parent is not the last dragged item. If you move 102, then attempt to add 101 to 102, the operation is successful.

These bugs (as far as I can tell) only occur on the root level. Logging dragInfo at line 1147 (in dragEnd) shows that dragInfo holds the incorrect index on drop. 

This bug was reproduced across computers, using the latest versions of Chrome, Safari, and Firefox.

**Comment by Voles** [comment]
We're currently at v2.8.0. Please re-create an issue if this still occurs.
