### ISSUE TITLE
Lazy load tree items example code

### ISSUE THREAD

**Issue by joschi127** [angular-ui-tree/angular-ui-tree#239]
Do you have some example code how to do this the right way? Would be great if you have something. But if not please feel free to just close this issue.

Thanks a lot!

**Comment by takeit** [comment]
@nicklasb what about drag and drop? is it working properly for you ? I have implemented restangular also, but when I have 

```
1                    
      1.1              
      1.2   
```

and when I want to move 1.2 under 1.1 I cant, because it looks like ui-tree doesnt know there is a child (this 1.1)

**Comment by nicklasb** [comment]
@takeit, no, you are right, it doesn't. I have the same problem as you. 

The component only allows me to drop among already expanded children. To put it another way, I can only drop beside an existing leaf node, never below it.

**Comment by nicklasb** [comment]
On the example, there seem to be some shadow graphic that indicates on what level an item will be dropped, I don't have that, there might be some .css or setting-issue.
http://jimliu.github.io/angular-ui-tree/tree.html

**Comment by takeit** [comment]
hmm maybe it possible to edit this scope responsible for drag & drop and somehow allow it to place the node below..

**Comment by lamemmv** [comment]
Hi everybody,

I have tried code of @joschi127 . But I have got the error when reading scope.

$scope.toggleChildren = function (scope) {
            if (!scope.$nodeScope.$modelValue.children) {
                scope.$nodeScope.$modelValue.getList("children").then(function (data) {
                    scope.$nodeScope.$modelValue.children = data;
                    if (scope.$nodeScope.$modelValue.children.length > 0) {
                        scope.toggle();
                    }
                });
            } else {
                if (scope.$nodeScope.$modelValue.children.length > 0) {
                    scope.toggle();
                }
            }
        };

scope.$nodeScope is undefined. what was I missing?

Thanks in advance.

**Comment by Voles** [comment]
We currently have no example on lazy loading data. More suggestions are welcome, so we can update the examples website with this! I'm closing this issue for now.

**Comment by vijender1256** [comment]
@Voles I am looking for a treeview where child nodes are retrieved from the API call and appended to the parent, for this first time all parent nodes are populated and when u click on parent node it should make a API call to get all the child nodes for that parent node and populate it,

Do you have any implementation demo anywhere, all the examples I am seeing are just retrieving data in one shot with parent child relationship and loading them at once. I wish to make an API call to get child elements, any help is appreciated thank you :)

**Comment by nicklasb** [comment]
Well, one of my projects, MBE-nodes, does this. 
It is, 1) written in typescript, and 2) not a very minimal example at all.
It is a generalized interface to a mbe, a backend built around MongoDB.

Either way, it *is* lazy loading. The onAsyncToggleChildren is called when the expander is clicked.
https://github.com/OptimalBPM/mbe-nodes/blob/master/src/controllers/schemaTreeController.ts#L351

**Comment by nitinba** [comment]
@joschi127 Thanks for  data-collapsed="!item.expanded", worked great.
