### ISSUE TITLE
Initially collapsed and load sub-nodes on demand (API requests)

### ISSUE THREAD

**Issue by gregoryRednet** [angular-ui-tree/angular-ui-tree#250]
Hi,

My tree view is initially collapsed because i have only loaded node level 1. Every nodes has a boolean attributes named has_children. I used the condition

```javascript
ng-if="(child.childs && child.childs.length > 0) || child.has_children"
```

to print the glyphicon-chevron and use 

```javascript
<li [...] data-collapsed="true">
```

to collapse nodes by default as you said in https://github.com/JimLiu/angular-ui-tree/commit/338e83047f58f4c9e1b343c57d5d35b3c10471a1

It works fine except when i drag & drop a node. This action collapse the node. If think the DOM is build everytime you change something and the node take the initial state (collapsed).

Maybe I'm missing something obvious? Thanks

**Comment by brianfeister** [comment]
@tvervest @gregoryRednet @Voles does anyone know the status of this?  I think with the v2.0 that was added and then backed out by @JimLiu, this feature was lost?  At least setting `data-collapsed="true"` doesn't do anything for me in `2.1.5` (which I was previously on) or `2.6.0` which I just updated to.
