### ISSUE TITLE
Cannot read property '$$hashKey' of undefined

### ISSUE THREAD

**Issue by dragonfire1119** [angular-ui-tree/angular-ui-tree#252]
I'm getting errors on the start up of the ui-tree.

``Cannot read property '$$hashKey' of undefined``

Then when I try to move the nodes around I get.

``Uncaught TypeError: undefined is not a function``

I seen that you fixed this in other issues but I can't seem to fix it on my end. 
https://github.com/JimLiu/angular-ui-tree/issues/242
https://github.com/JimLiu/angular-ui-tree/issues/159

It shows the first level nodes also.

Thanks for any help.

```
AngularJS v1.2.25
Angular ui tree v2.1.5
Bower install
```

Fixed
=====
I seen that you have to get the fix from https://github.com/JimLiu/angular-ui-tree/pull/192/files. It seems like the bower install is behind. The bower needs to be updated so Ill leave this open for a reminder thanks for angularjs ui tree.

**Comment by jacobscarter** [comment]
bower is up to date @StefanCodes this can be closed.
