### ISSUE TITLE
Roadmap to next release

### ISSUE THREAD

**Issue by NickPadilla** [angular-ui-tree/angular-ui-tree#254]
Hello,

I have been using this directive for a little while, but have found issue #199 to be affecting our application.  I have also seen a lot of movement on the project in the past months.  Is there any timeframe for the next release?  

Thanks!
Nick

**Comment by StefanCodes** [comment]
Development is progressing slowly on this project, but it is still moving forward. There's no roadmap, however - just a long list of open issues!
Closing this issue since it was based on a roadmap.
