### ISSUE TITLE
Unit Tests Failing w/Master branch

### ISSUE THREAD

**Issue by NickPadilla** [angular-ui-tree/angular-ui-tree#255]
Hello @JimLiu ,

The master branch is unstable, cannot run the unit tests successfully.  I am not sure if this is intended or if it was an oversight.  I'll try hunting down the problems but wanted to get more information about the current state of the project.  

Thanks! 
Nick

**Comment by jacobscarter** [comment]
Ticket is 2 years old and Unit Tests pass, @StefanCodes I think you can close this.

**Comment by StefanCodes** [comment]
@Voles rewrote a huge amount of the test infrastructure last year - this ticket ought to be resolved based on that.
