### ISSUE TITLE
Keep the dragged node in the source tree

### ISSUE THREAD

**Issue by skchi** [angular-ui-tree/angular-ui-tree#263]
Thanks for the wonderful directive.

Is it possible to keep the dragged node in the Source Tree?
I looked into the issue # 211 (https://github.com/JimLiu/angular-ui-tree/issues/211), saying its been implemented, but i don't see it being merged into the master.

Can you let me know this functionality is available.

Thanks
C

**Comment by enkodellc** [comment]
@uriklar this did not work for me. Any chance you can create a plunker for this?

**Comment by enkodellc** [comment]
I added cloning here https://github.com/angular-ui-tree/angular-ui-tree/pull/411

**Comment by jacobscarter** [comment]
@StefanCodes @Voles cloning is a thing so this can be closed.

**Comment by StefanCodes** [comment]
Confirmed #411 was merged by @Voles.
