### ISSUE TITLE
How cancel drop node

### ISSUE THREAD

**Issue by ofirrifo** [angular-ui-tree/angular-ui-tree#276]
Thanks for this library.
I have 2 tree.
I allow to drag node from tree a to tree b only.
is there an option to cancel drop node after I set accept callback to true in tree b when the node is out from the tree area?

**Comment by mattdarveniza** [comment]
This works however seems pretty hacky. Would be nice if the event had a `preventDefault` method or something to that effect.

**Comment by AndrewIsh** [comment]
@mattdarveniza +1

**Comment by StefanCodes** [comment]
https://github.com/angular-ui-tree/angular-ui-tree/pull/589 address this, but is not yet merged.

**Comment by AndrewIsh** [comment]
Aha, thanks for the heads up :)

**Comment by Voles** [comment]
#589 has been merged
