### ISSUE TITLE
version v2.2 status

### ISSUE THREAD

**Issue by equilerex** [angular-ui-tree/angular-ui-tree#285]
the demo of ui tree is using version 2.2, even though the latest listed is 2.1.5
what is the status of it? is it still a work in progress or more or less up to date version?
i've been trying to use it since it has the drag-distance feature that lets me use click events on the tree nodes since it avoids the instant drag. there is however some undesired functionality that i cant get around... when you set max depth, the dragging allows the node to be dropped only in the beginning (0) of the valid root node if you have reached the "max-depth" in the root node  (normally on 2.1.5 the placeholder would shift between the nodes withing the root so you could position it exactly where you want and it also gives a more constant and smooth feel of the dragging) ive been trying to both port the drag distance to 2.1.5 and fix the max depth issue but no luck so far since the drag distance seems like a fairly complex add on and the depth issue is probably not related to the depth itself but to some rewritten index handling in another feature(seems like a major overhaul) so pinpointing it has not worked so far

**Comment by ernestopye** [comment]
+1

**Comment by honkskillet** [comment]
Jim answered these questions here.
https://github.com/JimLiu/angular-ui-tree/issues/319
This issue could probably be closed.
