### ISSUE TITLE
Initiate the tree fully collapsed

### ISSUE THREAD

**Issue by webchaz** [angular-ui-tree/angular-ui-tree#290]
Is there a way to initiate the tree with all nodes collapsed? It seems by default that all of the nodes are expanded.  I've tried adding `data-collapsed` to the `ui-tree-node` but this doesn't seem to work.

**Comment by tvervest** [comment]
Hey @webchaz, I'm trying the same thing - with no success. Could you comment on how you solved or worked around this problem?

**Comment by sclearion** [comment]
Worse docs ever
