### ISSUE TITLE
Drag & drop does not work when using Angular 1.3 debugInfoEnabled(false)

### ISSUE THREAD

**Issue by jukkasi** [angular-ui-tree/angular-ui-tree#298]
Using Angular 1.3 optimizations (https://docs.angularjs.org/guide/production, $compileProvider.debugInfoEnabled(false);) drag and drop does nothing and it does not give any errors either.

I believe the ui-tree code is using some Angular features that are for debugging purposes only and not for production use.

At least element.scope() calls should not be used

**Comment by kether667** [comment]
+1

**Comment by jukkasi** [comment]
I see there are more and more .scope() calls since 2.1.5 release in master now. Probably these will be very hard to fix afterwards.

**Comment by Yankovsky** [comment]
+1
It was very hard to find bug on production.

**Comment by jukkasi** [comment]
2.1.5 had two .scope() calls which break in non-debug mode. 2.2.0 has 21 calls..

**Comment by Yankovsky** [comment]
Maybe we can use element.controller() instead. It is available even with debugInfoEnabled(false).
https://docs.angularjs.org/api/ng/function/angular.element#methods

**Comment by morgenes** [comment]
+1 this is impacting our application

**Comment by rpinto** [comment]
any fix on this yet?

**Comment by jukkasi** [comment]
@JimLiu Any ideas how to access correct scope without using .scope() method for elements?

**Comment by Wlada** [comment]
+1

**Comment by asaarnak** [comment]
+1

**Comment by rpinto** [comment]
no fix on this yet?

**Comment by StefanCodes** [comment]
This is fixed in https://github.com/angular-ui-tree/angular-ui-tree/pull/596 but not yet merged to master.

**Comment by Voles** [comment]
@rpinto / @StefanCodes I've created a PR with the fix. It's ready to be reviewed!

**Comment by TopGunBasten** [comment]
it is also cannot working with angularjs 1.3.13

**Comment by Voles** [comment]
Fixed with #648 and available since v2.15.0
