### ISSUE TITLE
Drag and reorder not working in Firefox after scrolling horizontally

### ISSUE THREAD

**Issue by tomcully** [angular-ui-tree/angular-ui-tree#323]
Hi,

I'm working on an app that scrolls horizontally. Trees that are visible before scrolling can be reordered, however, the same tree cannot be reordered if you scroll horizontally. This only affects firefox.

I've noticed that the "target area" for the drag and drop functionality is still there after scrolling, however, it is no longer aligned with the ui-tree.

I have created this gist to reproduce the issue: https://gist.github.com/tomcully/e13558ab2a9a6c53a143

Is there a known "fix" for this?

Thanks,

Tom

**Comment by nickdrummond** [comment]
We are seeing the issue in 2.1.4/2.1.5
I narrowed this down to ui.tree dragMove
The calculation of the location of the draggable was not taking into consideration the difference between Chrome and FF

`var targetX = eventObj.pageX - $window.document.body.scrollLeft;`

`$window.document.body.scrollLeft` is always 0 for FF.

It can be fixed consistently with your code in other places.
```javascript
var targetX = eventObj.pageX - (window.pageXOffset || $window.document.body.scrollLeft || $window.document.documentElement.scrollLeft);
var targetY = eventObj.pageY - (window.pageYOffset || $window.document.body.scrollTop || $window.document.documentElement.scrollTop);
```

However, the codebas has moved on and it looks like this has changed in master (which we couldn't get to work). We're probably going to just take a snapshot and put the fix in for now.

**Comment by tomcully** [comment]
No probs :+1: Will look at some of the issues on the list when I get a sec :)
resolve #323

**Comment by tomcully** [comment]
resolved in pull request [626](https://github.com/angular-ui-tree/angular-ui-tree/pull/626)
