### ISSUE TITLE
Adding nodes by form input

### ISSUE THREAD

**Issue by kotmatpockuh** [angular-ui-tree/angular-ui-tree#324]
Hello.
Maybe anybody could counsult how to add or delete or edit nodes with this code with the help of <form> tag? In doc there is no information about that...

**Comment by kotmatpockuh** [comment]
with add and delete i solved... but with editing have troubles... : (

**Comment by nobalmohan** [comment]
Can you share how did you do add / delete ?

**Comment by kotmatpockuh** [comment]
@nobalmohan maybe U better create fiddle and i take a look there?

**Comment by nobalmohan** [comment]
U just need to pass scope  and your form input 

           var nodeData = scope.$modelValue;
           var formInputValue = InputData;
             nodeData.subFolders.push({
                    id: '123',
                    folderName: InputData,
                    subFolders: []
                });

**Comment by kotmatpockuh** [comment]
did you solve it? 
here is part of my code:


for subitems:
        `nodeData.Options.push({
          'Content': $scope.note.Content,
          'Title': $scope.note.Title,
          'Options': $scope.note.Options
        });`

for items:
just clear post request:
`$http.post('/app/' + $scope.Id + '/articles', $scope.note,...`

**Comment by nobalmohan** [comment]
For my use case, I did solve it. You can close this ticket !
