### ISSUE TITLE
How to expand specific node

### ISSUE THREAD

**Issue by mschuler** [angular-ui-tree/angular-ui-tree#325]
I can enumerate through all my nodes in the tree this way:

    var nodes = angular.element('#tree-root-' + website.id + " [ui-tree-node]");
    for(var i = 0; i < nodes.length; i++) {
        var node = nodes[i];
    }

Now I want to get the scope of the node and maybe expand it. How is that possible? `node.expand()` is undefined, `node.scope()` too.

**Comment by nobalmohan** [comment]
Do you want to iterate all your node and expand ? If not, you can use this,

    $scope.collapseAll = function() {
      $scope.$broadcast('collapseAll');
    };

    $scope.expandAll = function() {
      $scope.$broadcast('expandAll');
    };

**Comment by mschuler** [comment]
Hi Nobal, thank you for your answer.
I know these broadcast events, but as you already note, they expand or collapse the whole tree. I only want to expand/collapse specific single nodes.
I need this to implement a search function. When searching with a string, I collapse the whole tree and then expand only the matching nodes.

**Comment by nobalmohan** [comment]
Got it. I think, you can follow this approach, its a nasty hack

1. Call a custom expand function for each node. ng-click="CustomExpand(this)"
2. CustomExpand will be triggered only on true of some variable, say "SearchStringFound". ng-click="SearchStringFound || CustomExpand(this)"
3. Iterate the tree and if matching search node found. Set the SearchStringFound to true
4. Set $scope.SearchStringFound = false onload

In controller, 
$scope  CustomExpand = function(scope) {
      scope.expand();
      //if not $nodeScope.expand();
}

**Comment by sebver** [comment]
I had this problem today as well, this was my approach:

I basically iterate the whole tree, using the childNodes() function until I find the requested node, collecting the parent scopes along the way.

I then expand all the ancestors and the requested node (it's no use expanding a node if its parent is collapsed).

I have a plunker here: http://plnkr.co/edit/5EQu0mtpaOQOuJtLeH0t?p=preview

Don't know if there is an an easier/better way though.

**Comment by nobalmohan** [comment]
@mschuler @sebver I think for any given node, the combination of depth, index is unique (                 scope.$nodeScope.depth(), scope.$nodeScope.index() ). So, you can use them for condition checking in view and trigger a click event to expand !

**Comment by mschuler** [comment]
Thank you @sebver, your plunker helped me to solve my problem!

**Comment by crackedcornjimmy** [comment]
Why might the following line of code return an empty set when the tree is visible in the UI?

return angular.element(document.getElementById("tree-root")).scope().$nodesScope.childNodes()[0]

My problem is published here: https://stackoverflow.com/questions/47933196/how-to-expand-a-default-angular-ui-tree-node

**Comment by meswain1123-zz** [comment]
I got @sebver's version working with a little tweaking.   

In getScopePathIter I had to change

`var childNodes = scope.childNodes();`

to 

`var childNodes = scope.$element[0].children[1].children;`

I did that because the original was giving an array where all the elements were the same.  This made it give me an array of html elements.

Then I changed the for loop from 

 ```
 for (var i = 0; foundScopesPath === null && i < childNodes.length; i++) {
            foundScopesPath = getScopePathIter(nodeId, childNodes[i], newParentScopeList);
        }
```

to 

```
for (var i = 0; foundScopesPath === null && i < childNodes.length; i++) {
                var childNode = angular.element(childNodes[i]).scope();
                foundScopesPath = getScopePathIter(nodeId, childNode, newParentScopeList);
            }
```
so it would take the html elements and get their corresponding scopes.

Hope that's helpful.

**Comment by rahi-rajeev** [comment]
HI, matt,
 i have problem suppose i have a page which user can select and then save so
after save page will reload, in case its not working properly if am going to hard refresh then work
![system configuration](https://user-images.githubusercontent.com/15867058/38172528-5b0fe8bc-35cb-11e8-9575-1cef3a21ab54.png)

**Comment by spankyed** [comment]
This issue would be trivial if there was a getNodeScopeById API.
