### ISSUE TITLE
Expanding a node on dropped

### ISSUE THREAD

**Issue by uriklar** [angular-ui-tree/angular-ui-tree#329]
Hi guys,
I've been trying everything I can think of but can't get a node to expand on drop. My node have: ``` data-collapsed="true" ``` so they'll be collapsed by default.
 In ```beforeDrag``` I've managed to do: ```sourceNodeScope.collapsed = false; ```
and the node actually expands. But in the dropped event I try to do:
``` event.source.nodeScope.collapsed = false; ```
and nothing happens. Any ideas? I also tried ``` expand() ```

**Comment by nobalmohan** [comment]
Did you try "beforeDrop" event instead of "dropped" ? As per documentation, dropped is only called when the position of dropped node changes !

**Comment by Voles** [comment]
Closed due to inactivity.
