### ISSUE TITLE
Prevent dragging outside root node

### ISSUE THREAD

**Issue by yccteam** [angular-ui-tree/angular-ui-tree#334]
Let's say I have this model:
```items = [
{
 id: 'root', 
 title: 'root', 
 items: [
  {
   id: 'child1', title: 'child1'
  }
 ]
}
];```
How can I prevent dragging child1 outside of of root node?

**Comment by adri** [comment]
Mh do you think this is related to #317?

**Comment by yccteam** [comment]
It now works for me.
All I had to do was remove the place holder (so you can't add new roots) and make sure you can't switch away from your root (in the case there are many roots) in my accept function (by adding some meta data to my roots and nodes - telling which node belongs to which root).
Thanks :)
