### ISSUE TITLE
Broken Tree - demo

### ISSUE THREAD

**Issue by sheymann** [angular-ui-tree/angular-ui-tree#336]
1. Go to http://angular-ui-tree.github.io/website/tree.html
- click on a Remove button using either a mouse or pad

The item is dragged and the button is never clicked.

**Comment by x7ian** [comment]
You need to add Drag Delay to your ui-tree element like this:

<div ui-tree="treeOptions" data-drag-delay="500"> ...

so that the handler grab action has a delay before taking affect, alowing the node buttons to work.

**Comment by Voles** [comment]
The example pages have been updated, please see http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example
