### ISSUE TITLE
nodrop doesn't work anymore (v2.1.5)

### ISSUE THREAD

**Issue by guynamededd** [angular-ui-tree/angular-ui-tree#347]
In a previous commit the nodrop functionality was supposedly fixed.

https://github.com/angular-ui-tree/angular-ui-tree/commit/1ff9a99661d6467aec5648bff03130cd3430075c

When I checked for the code that was fixed in that commit it was missing from the current version. Now the nodrop attribute on the uitreenodes scope is never getting set.

            scope.$watch(function() {
             return scope.$eval(attrs.maxDepth);
           }, function(newVal) {
             if((typeof newVal) == "number") {
               scope.maxDepth = newVal;
             }
           }, true);

           scope.$watch(function () {
           return attrs.nodrop;
           }, function (newVal) {
           if((typeof newVal) != "undefined") {
             scope.nodrop = true;
             }
           }, true);

**Comment by kwieckowski-neducatio** [comment]
Hi,
Can we have a release with this fix please?
Thank you!

**Comment by honkskillet** [comment]
+1 for 2.1.6

**Comment by enkodellc** [comment]
Please test this PR. I fixed the nodrop and added a clone attribute. https://github.com/angular-ui-tree/angular-ui-tree/pull/411

**Comment by honkskillet** [comment]
+1
