### ISSUE TITLE
2.2.0 upgrade callbacks not triggered

### ISSUE THREAD

**Issue by h960087** [angular-ui-tree/angular-ui-tree#351]
Hi,

I just upgraded to 2.2.0 to be able to use the stable drag-delay feature for clicking on draggable nodes, but the dragStart, dragStop, dropped callbacks are not working now.
Am I missing some changes? with 2.1.5 everything is ok except the drag-delay not allows to click on nodes.
Thanks for your help!

**Comment by JimLiu** [comment]
Sorry something changed on 2.2.2
Please check the newest document about callback:
https://github.com/angular-ui-tree/angular-ui-tree#callbacks-type-object

**Comment by h960087** [comment]
Hi,

Thanks, but I still can't see where i fail. Can you point out?

My code is like:

HTML:
<div ui-tree="templateTree">
	<ol ui-tree-nodes ng-model="template.nodes">
		<li ng-repeat="fragmentNode in template.nodes" ui-tree-node
			data-collapsed="fragmentNode.collapsed"
			ng-include="*/template-tree-details.html'"></li>
	</ol>
</div>

JS:
		$scope.templateTree = {
				dragStop: function(event) {
					console.log("drag stop");
					},
				dragStart: function(event) {
                                        console.log("drag start");
                                        }
		};

**Comment by JimLiu** [comment]
Can't see your html

**Comment by h960087** [comment]
Sorry, updated!

**Comment by h960087** [comment]
Hi,

I could spot the difference, i have to write ui-tree callbacks="" instead of ui-tree="". It fixed my issue.
It was such a little change in the readme, that my eyes just slipped throught it.

Thanks for your help, and for the module!
