### ISSUE TITLE
In version v2.2.0 'data-nodrag' doesn't work

### ISSUE THREAD

**Issue by natee** [angular-ui-tree/angular-ui-tree#356]
Demo page angular-ui-tree version is v2.0.13,it works,but on master branch,it seems doesn't work.

demo : http://jsbin.com/zaxubaneno/1

**Comment by natee** [comment]
When the tag like '<span data-nodrag>' ,the attr is 'data-nodrag' ,absolutely `typeof targetElm.attr('nodrag')` will be undefined.

```js
/**
 * @ngdoc method
 * @methodOf ui.tree.service:$nodrag
  * @param  {Object} targetElm angular element
  * @return {Bool} check if the node can be dragged.
  */
  nodrag: function (targetElm) {

       return (typeof targetElm.attr('nodrag')) != "undefined" || typeof targetElm.attr('data-nodrag') != "undefined";
  },
```

**Comment by JimLiu** [comment]
I'll check that, thanks!
And welcome to pull request :)

**Comment by martinlingstuyl** [comment]
I ran into that as well Jim. I routed it to line 926.
When I clicked on an element of which one ancestor had the nodrag attribute, it didnt work. 

```javascript
"// check if it or it's parents has a 'nodrag' attribute
while (eventElm && eventElm[0] && eventElm[0] != element) {
      if ($uiTreeHelper.nodrag(eventElm)) { // if the node mark as `nodrag`, DONOT drag it.
         return;
     }
     eventElm = eventElm.parent();
}
```

When I added this super dirty fix around line 904 :) it started working:

```javascript
// If nodrag attribute = available on target or parent dont drag
if (scope.$treeScope.dragEvent.target.parentNode.outerHTML.indexOf("data-nodrag") > -1) {
return;
}
```

**Comment by martinlingstuyl** [comment]
Ah, correction. I see that changing the nodrag: function (targetElm) fixes the bug indeed.
