### ISSUE TITLE
2.2.0 Placeholder doesn't always move with cursor

### ISSUE THREAD

**Issue by martinlingstuyl** [angular-ui-tree/angular-ui-tree#358]
With 2.0.13 (the version used on the demo site) the placeholder moves nicely with the cursor as you move an item across the tree.

When I installed it however, (that installed version was 2.2.0) the placeholder only moved with the cursor on the first level of nodes. On the second level the placeholder simply remained static at the position the item originally was. This was when I had a 2layer deep tree.
When I had a single layer tree, the problem showed as well: the placeholder now didnt move with the cursor on the first level.

When I swapped the js file with the js file used on the demopage, it worked as it should.
![example](https://cloud.githubusercontent.com/assets/5267487/6056863/329296cc-ad17-11e4-9645-f07b9d5118e6.png)

for my project, I tried using 2.0.13, but it appears the dropped event wasn't working there, so no luck. I'm stuck with 2.2.0 and hopefully you'll fix this in time for me to go live with the fix.

For the rest: great project, thanks for all the effort!

**Comment by JimLiu** [comment]
I can't reproduce that, could you give me a demo ?

**Comment by bulkan** [comment]
@JimLiu to reproduce this just update the version of ui-tree used in your examples http://angular-ui-tree.github.io/website/trees.html

**Comment by martinlingstuyl** [comment]
You tried that out, I presume, Bulkan? (that spares me the work of reproducing, thanks!)

**Comment by bulkan** [comment]
@martinlingstuyl I copied the view for the connected trees and ran it with v2.2.0

**Comment by bulkan** [comment]
I've created two short videos demonstrating this problem using the trees demo in the website repo. There is one difference and that is `data-max-depth=1` is set on the tree2's `ui-tree`

[This](https://www.youtube.com/watch?v=-JsJhciRnyA&feature=youtu.be) is using 2.1.5 and [this](https://www.youtube.com/watch?v=ThCCEV4xtiU&feature=youtu.be) video is using 2.2.0 and you can see the placeholder isn't showing

**Comment by JimLiu** [comment]
OK, I'll test it on the demo site.

**Comment by JimLiu** [comment]
Rollbacked to v2.1.5 , so there is no problem now.
Please rollback your changes, sorry about that!

**Comment by martinlingstuyl** [comment]
Ok, will do. I hope the dropped event is working there? The last time i
checked 2.0.13. I couldnt get it to work.
Will try that out asap.

Martin
Op 6 feb. 2015 18:46 schreef "Jim Liu" <notifications@github.com> het
volgende:

**Comment by equilerex** [comment]
I suspect the issue is when you have a custom "accept" configuration... if you return true on the destination parent itself but false on the nodes inside the parent, they seem to conflict so the node's "false" will always win... heres a plnkr to illustrate the issue for when you try to compile a new 2.20 again ;) theres a commented out 2.25 in the plnkr ... replace 2.20 with that to see that it worked on the previous version.

http://plnkr.co/edit/NsEzJhJx7eNws4gfiHU0?p=preview

**Comment by martinlingstuyl** [comment]
Hmm..
I see that the left example works as it should.
But the right example doesn't work at all.
In my case I could drop items in the sublists and switch their positions, I
just had to overlook the placeholder issue. which isnt very userfriendly.

Plus, I didn't have a custom Accept function in the first place.

So my question is: why is your left example working?!?!



2015-02-09 11:18 GMT+01:00 Joosep Kõivistik <notifications@github.com>:

> I suspect the issue is when you have a custom "accept" configuration... if
> you return true on the destination parent itself but false on the nodes
> inside the parent, they seem to conflict so the node's "false" will always
> win... heres a plnkr to illustrate the issue for when you try to compile a
> new 2.20 again ;) theres a commented out 2.25 in the plnkr ... replace 2.20
> with that to see that it worked on the previous version.
>
> http://plnkr.co/edit/NsEzJhJx7eNws4gfiHU0?p=preview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui-tree/angular-ui-tree/issues/358#issuecomment-73485506>
> .
>



-- 
Martin Lingstuyl
Webdeveloper
Interactive Webdesign
interactivewebdesign.nl


<http://interactivewebdesign.nl>

**Comment by equilerex** [comment]
right one works, it just doesn't insert a placeholder (if you drop it, it will go more or less into the right place... on my own production code, it would actually show the placeover the same way as in you case... drags just to the beginning or end of a sub node but not between other nodes, not sure why its not like that on the plnkr)

left side is just standard functionality... do you have any extra configuration applied to it?
in 2.20 it seems like you need   callbacks="TreeOptions" instead of  ui-tree="TreeOptions" maybe that has something to do with it?

**Comment by martinlingstuyl** [comment]
Thats weird then,

the right one doesnt work with me (tested in firefox and IE) It does not
drop the item at the preferred place as you say it does with you.
the left one works as it should, but differently than my own version. I
don't think I changed anything meaningful, plus: Bulkan confirmed the wrong
behavior using Jims tree-example coupled with the 2.2.0 script.

Martin

2015-02-09 12:06 GMT+01:00 Joosep Kõivistik <notifications@github.com>:

> right one works, it just doesn't insert a placeholder (if you drop it, it
> will go more or less into the right place... on my own production code, it
> would actually show the placeover the same way as in you case... drags just
> to the beginning or end of a sub node but not between other nodes, not sure
> why its not like that on the plnkr)
>
> left side is just standard functionality... do you have any extra
> configuration applied to it?
> in 2.20 it seems like you need callbacks="TreeOptions" instead of
> ui-tree="TreeOptions" maybe that has something to do with it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui-tree/angular-ui-tree/issues/358#issuecomment-73491618>
> .
>



-- 
Martin Lingstuyl
Webdeveloper
Interactive Webdesign
interactivewebdesign.nl


<http://interactivewebdesign.nl>

**Comment by derek-adair** [comment]
Here is this bug in gif version... still around in 2.16.0.  I will be attempting to slay this bug along with #777 if anyone has a fix hidden in their pocket that'd be really F@!$ing rad :)

**Comment by carolinagc** [comment]
I'm also running with similar problems, the place holder does position correctly with the cursor.
It does not allow to nest inside another node or it doesnt allow to unnest and put in a higher level the node. Also is arbitrary when it happens and in which position of the tree.

**Comment by Voles** [comment]
@derek-adair @carolinagc this issue is quite dated so I suggest we'll move further discussions about this issue to #777. Or are there any other issues pointed out here?

**Comment by carolinagc** [comment]
@Voles ok, we can move the discussion to #777
