### ISSUE TITLE
Cant drop nodes into empty tree

### ISSUE THREAD

**Issue by bulkan** [angular-ui-tree/angular-ui-tree#361]
This is using v2.2.0 with a manual change to the code to set the default value in this line to true https://github.com/angular-ui-tree/angular-ui-tree/blob/4725bdb642a508fb92bf54dfea2d2049e319eb7e/source/controllers/treeCtrl.js#L19

See this video of the behavior https://www.youtube.com/watch?v=veLQyLCtETY&feature=youtu.be

**Comment by JimLiu** [comment]
Hi @bulkan 
I rollback to v2.1.5 now. #362

**Comment by bulkan** [comment]
@JimLiu I'll close this off now as it's not relevant to 2.1.5. Thanks
