### ISSUE TITLE
2.1.5. Dropped Event not working

### ISSUE THREAD

**Issue by martinlingstuyl** [angular-ui-tree/angular-ui-tree#364]
Hi Jim,
Okay, so I tried it out. Unfortunately, the custom dropped event doesnt seem to kick in.
The dropped event within the file kicks in alright. But the $scope.options dropped event I added doesnt. (it did in 2.2.0, so I know the code is alright in principle.)

Hope you can check this out! 

The placeholderbusiness works perfectly now!

thanks!
Martin

**Comment by martinlingstuyl** [comment]
Ok, I think I fixed it myself just now:

Line 722 
```Javascript
scope.$watch(attrs.callbacks, function(newVal, oldVal){
            angular.forEach(newVal, function(value, key){
              if (callbacks[key]) {
                if (typeof value === "function") {
                  callbacks[key] = value;
                }
              }
            });
```

it watched for attrs.uiTree. I thought it should be attrs.callbacks, since thats what it will be looping in the forEach. After I changed it the custom dropped event started working.

**Comment by JimLiu** [comment]
Got it, will be fixed in next version.
