### ISSUE TITLE
Duplication of node

### ISSUE THREAD

**Issue by abbasikov** [angular-ui-tree/angular-ui-tree#367]
i have enabled drag functionality of the tree. but when i click on any node that node is duplicated. and this is done when i do inline editing of the node. anyone knows how fix this issue ?

**Comment by bulkan** [comment]
Which version of angular-ui-tree are you using ? Can you please provide some code on plunkr/jsbin etc ?

**Comment by abbasikov** [comment]
m using v2.2 of ui-tree. 

http://plnkr.co/edit/Hy0vnsGq9rUnrEfDih8b

**Comment by bulkan** [comment]
2.2 has been rolled back because of a few bugs https://github.com/angular-ui-tree/angular-ui-tree/issues/362

**Comment by JimLiu** [comment]
Yes, please try v2.1.5. 
Thanks @bulkan !

**Comment by abbasikov** [comment]
Thanks alot. It worked for me.
