### ISSUE TITLE
expand on hover over 

### ISSUE THREAD

**Issue by boris-petrov1214** [angular-ui-tree/angular-ui-tree#372]
can folder be expanded automatically when hover hover?

**Comment by JimLiu** [comment]
I'll try to merge this from v2.2.0

**Comment by boris-petrov1214** [comment]
Thanks.
When can we expect expand on hover hopefully?

**Comment by devmark** [comment]
fixed already?

**Comment by websirnik** [comment]
@Voles is it possible to merge https://github.com/rd-dev-ukraine/angular-ui-tree/commit/74aae11a95976abc6036e3b520218cba85f51da3?

**Comment by jacobscarter** [comment]
This should be working in latest release of angular-ui-tree
