### ISSUE TITLE
"dropped" callback not being called in v2.2.0

### ISSUE THREAD

**Issue by spencerwi** [angular-ui-tree/angular-ui-tree#374]
I see #362, so I know you're aware that 2.2.0 is broken.

That being said, I've found another bug in v2.2.0 (if you `bower install angular-ui-tree`, you still get v2.2.0, which is how I got v2.2.0 instead of v2.1.5):

`dropped` callbacks designated in the tree options object (which, as an aside, should probably be documented somewhere) are not being called:

http://plnkr.co/edit/tguImxZCHyufJV18QQ77?p=preview

**Comment by JimLiu** [comment]
Yes, this is a bug, it was fixed in #364.

I'll try to release the new version ASAP.

**Comment by spencerwi** [comment]
Ah, didn't see that issue. Thanks.
