### ISSUE TITLE
Is there a way to drag a node but having it remain?

### ISSUE THREAD

**Issue by nicklasb** [angular-ui-tree/angular-ui-tree#375]
Of course, I may have missed it, but I haven't found any information on this.

What I am after is mostly having a tree as a persisting source of stuff to drag into another tree, but also functionality like ctrl-dragging, indicating a copying of nodes.

I have seen issue #165, but that seems like a solution that would trigger updates and perhaps result in a somewhat flickering user experience. 

Is there something like that, or perhaps something planned?

**Comment by jacobscarter** [comment]
data-clone-enabled takes care of this

**Comment by nicklasb** [comment]
@jacobscarter 
Ok,maybe a dumb question, but doesn't setting that to false stop the cloning? So that it isn't being copied and ends up being moved instead? Because if it doesn't, it should be called something else?

**Comment by jacobscarter** [comment]
Yes if clone is false it moves the node. If clone is true then it copies the node and doesn't move the original
