### ISSUE TITLE
Is there any way to get the bradcrumb of selected node ?  Like: ROOT>CHILD3>CHILD1>CHILD5

### ISSUE THREAD

**Issue by stripathix** [angular-ui-tree/angular-ui-tree#387]

**Comment by honkskillet** [comment]
I would recursively traverse your underlying data structure until you find the target node.  Once it is found, start returning nodes, pushing each onto a return array.  Something like.

```
//should yield an array of nodes of form [root, daughter1, daugher2,.... ,selectedNode]
//I haven't tested this yet, but you get the idea.  Basic recursion.
function getNodePathArray(root, selectedNode){
  for(int i=0; i <root.nodes.length;i++){
    if(root.nodes[i]===selectedNode)
     return [selectedNode];
    else{
       var path = getNodePathArray(root.nodes[i],selectedNode);
       if(path)
         return path.unshift(selectedNode); 
    }
  }
  return null;
}
```
Once you have the array of nodes, you can use a standard bootstrap (or whatever you prefer) breadcrumbs with ng-repeat.

This is outside the scope of this directive, however, and this issue should be closed. :)

**Comment by stripathix** [comment]
Thanks @honkskillet :-).
Found this awesome JS module: http://jnuno.com/tree-model-js/
