### ISSUE TITLE
Getting a "Uncaught TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by michaelryancaputo** [angular-ui-tree/angular-ui-tree#39]
Uncaught TypeError: Cannot read property '0' of undefined - On line 220.

I can't pinpoint why i'm getting this.

**Comment by Purewebdesign** [comment]
I know it's a long time ago, but perhaps people who are having the same issue in the future could be helped with what i'm going to tell. 

I had the same issue `"Uncaught TypeError: Cannot read property '0" of undefined"` 

The issue had to do with this code in my view and not with the digest ($apply):

```
<div ui-tree data-collapsed="true">
    <div ui-tree-nodes="" ng-model="data" id="tree-root">
        <div ng-repeat="label in labels" ui-tree-node ng-include="'app/views/partials/nodes_renderer.html'">
        </div>
    </div>
</div>
```

i copied this from an example i found on the internet and changed the `ng-repeat`. Everything worked except i got the error `"Uncaught TypeError: Cannot read property '0" of undefined"`, I spend a long time looking where this error could come from, but then i saw what i missed... i had to change the `ng-model="data"` to `ng-model="label"` to and that was all!

Hope it helps some other people!
