### ISSUE TITLE
Drag doesn't work with disabled debugInfo

### ISSUE THREAD

**Issue by chino23** [angular-ui-tree/angular-ui-tree#403]
Hi,

as recommended by angular to speed up things, in production the debug info can be disabled.

````
myApp.config(['$compileProvider', function ($compileProvider) {
        $compileProvider.debugInfoEnabled(false);
}])
````

However, then the dragging of nodes doesn't work anymore. Doesn't throw an error in the console, though.

Can this be fixed somehow?

**Comment by AlexanderKozhevin** [comment]
Agreed, that's fucking weird. 
Thanx that you posted it, otherwise I would never understood this bug.

**Comment by StefanCodes** [comment]
The ticket with the most exciting action on this issue is https://github.com/angular-ui-tree/angular-ui-tree/issues/521
