### ISSUE TITLE
Traversing tree?

### ISSUE THREAD

**Issue by vtmoren** [angular-ui-tree/angular-ui-tree#418]
Are there any examples of how to traverse an tree?
I am trying to change the color of a tree node when it is clicked.

Or is there an easier built in way to do this?

-VM

**Comment by vtmoren** [comment]
Does anyone have an answer for this?

**Comment by smahadevappa** [comment]
I also have a similar requirement. I am able to traverse from parent to child. But is there a way to traverse other way also? I mean find the parent of the child nodes

**Comment by honkskillet** [comment]
You'd use standard recursion to traverse the tree.  I made an example for issue #205 which might be helpful.
http://plnkr.co/edit/SBLjHW76yL3yfiDJYe0K?p=catalogue

**Comment by vtmoren** [comment]
Thanks you for the example.  Many tree widgets have built in method to traverse the tree.  Was just curious thats all.  I will use recursion.  Thanks!
