### ISSUE TITLE
Migrating from 2.1.5 to 2.2.0?

### ISSUE THREAD

**Issue by cjroth** [angular-ui-tree/angular-ui-tree#420]
I just upgraded from 2.1.5 to 2.2.0 and it broke quite a few things - one of which is that I needed to change the `data-nodrag` attribute to `nodrag`. Others I'm still debugging why they are broken and what I need to do to fix them. So two questions:

1. Is there a list of changes somewhere between 2.1.5 and 2.2.0 aside from the commit log?
2. Why wasn't this a full version bump (3.0.0)?

**Comment by cjroth** [comment]
Ugg scratch that. Apparently 2.2.0 is being unpublished?

**Comment by Voles** [comment]
The v2.2.0 version has been reverted by @JimLiu. A new version is in the making. In the meantime, you can keep using v2.1.5.

**Comment by Voles** [comment]
Version 2.3.0 has been released. Does the issue still occur?

**Comment by cjroth** [comment]
Seems to work fine with 2.4.0. Thanks!
