### ISSUE TITLE
$modelValue is underfined in 2.1.5 API Version.

### ISSUE THREAD

**Issue by hhalmeida** [angular-ui-tree/angular-ui-tree#422]
Hi... I Update to 2.1.5 and don't work this version.
it show this error::

Error: treeNodesCtrl.scope.$modelValue is undefined
$scope.init@http://localhost:2099/Web/App/Resources/js/angular/treeview/angular-ui-tree.js:494:17
.link@http://localhost:2099/Web/App/Resources/js/angular/treeview/angular-ui-tree.js:822:21
J@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:54:373
g@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:47:256
B/<@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:46:377
M/<@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:48:217
w@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:52:29
td</<.compile/</</<@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:197:226
p/g.success/<@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:72:199
De/e/l.promise.then/J@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:101:87
De/f/<.then/<@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:102:259
Yd/this.$get</h.prototype.$eval@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:113:28
Yd/this.$get</h.prototype.$digest@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:110:109
Yd/this.$get</h.prototype.$apply@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:113:360
m@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:72:452
w@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:77:463
ye/</B.onreadystatechange@http://localhost:2099/Web/App/Resources/js/angular/angular.min.js:79:24

What can I do regarding this case..?

**Comment by chino23** [comment]
some sample code would be nice

**Comment by kastoestoramadus** [comment]
I started working with angular-ui-tree. I got same error on copy paste of your tree demo.
All web browsers affected but with different messages.

**Comment by kastoestoramadus** [comment]
I started working with angular-ui-tree. I got same error on copy paste of your tree demo.
All web browsers affected but with different messages.

**Comment by Voles** [comment]
Please update to the latest release, v2.3.0. Let us know if this error still occurs after upgrading.
