### ISSUE TITLE
Angular directive does not work when $compileProvider.debugInfoEnabled(false);

### ISSUE THREAD

**Issue by jsfrocha** [angular-ui-tree/angular-ui-tree#425]
Angular developers recommend turning off debug info to speed up angular apps in production environments. Consequence of this action is that scope() functions stops working, because scope() functions are intended to be used only for development (and batarang extension). However, the angular-ui-tree directive drag and drop methods (which is where I experienced problems - simply stops working) depends heavily on scope() functions, so in production environments angular directive does not work.

Here is the official document stating these facts https://docs.angularjs.org/guide/production

To reproduce simply add `$compileProvider.debugInfoEnabled(false)` on the config method of the AngularJS Application. (Remember to inject `$compileProvider` into it)

Regards

**Comment by chino23** [comment]
I have the exact same problem. This module is the reason I can't disable it, which is a shame as the DOM is littered with useless debug info which makes it noticable slower. https://github.com/angular-ui-tree/angular-ui-tree/issues/403

**Comment by Voles** [comment]
I see we use the `scope()` method in `uiTreeNode.js` line 67 and 294. Any ideas on how to replace the usage of `scope()`?

**Comment by chino23** [comment]
@Voles I don't really know how to implement that.

But there was a similar issue at angular-ui-sortable. This is the PR that fixed it: https://github.com/angular-ui/ui-sortable/pull/314

**Comment by JustTSK** [comment]
+1 need fix for this.

**Comment by PSDCoder** [comment]
Maybe we can use solution from https://github.com/oori/ng-sortable/commit/433fa3770bd2778464cabe5d590beb034bacadef ?

**Comment by jsfrocha** [comment]
Looks good, at first glance.

**Comment by hworld** [comment]
This caught me a while ago, so I had to fork and commit a fix. I just recently merged in the latest version and things seem to be working still. You can see the fork at: https://github.com/gamejolt/angular-ui-tree

If you would like to see the hack that solved it, it's pretty similar to ui-sortable: https://github.com/angular-ui-tree/angular-ui-tree/compare/master...gamejolt:master

Note that I just committed against the dist folder for my purposes.

**Comment by papertrailrob** [comment]
I've just been scratching my head over this! Would be great to see a fix.
I could have a go at creating a pull request, unless anyone else already is?

**Comment by jukkasi** [comment]
+1

**Comment by jjulicher** [comment]
+1

**Comment by edbentinck** [comment]
+1 Would be great to see a fix for this soon!

**Comment by bkirtika** [comment]
+1

**Comment by Voles** [comment]
Please review: #596

**Comment by homerjam** [comment]
+1

**Comment by homerjam** [comment]
Would also need a way to obtain root scope - i.e. pass an object to use as scope to the tree through options.

**Comment by benpate** [comment]
+1

**Comment by Voles** [comment]
Closing, let's have further discussion in the PR containing a fix (work in progress for now). See #648.
