### ISSUE TITLE
$callbacks don't seem to work

### ISSUE THREAD

**Issue by HoplaGeiss** [angular-ui-tree/angular-ui-tree#432]
I am trying to detect a dragndrop event!

I will just paste you some of my code :

Parts of my template:

```
<div ui-tree="options">
   <ol ui-tree-nodes ng-model="list" >
      <li ng-repeat="item in list" ui-tree-node ng-include="'items_renderer.html'"></li>
    </ol>
</div>
```

```
<ol ui-tree-nodes="options" >
      <li ng-repeat="item in item.items" ui-tree-node ng-include="'items_renderer.html'" ></li>
 </ol>
```

Part of my controller:

```
 $scope.options = {
    dropped: function(event) {
      console.log(event);
   }
 };

```

What is wrong with this ?
Nothing gets logged in my console

**Comment by scarber777** [comment]
I ran into this issue as well. I've put the following in my code for now:

            var setCallBacks = function () {
                var treeScope = getRootNodesScope();
                var callBacks = treeScope.$callbacks;
                callBacks.dropped = function (event) {
                    setOrdinals(treeScope.$nodesScope.$nodesMap);
                };
            };

**Comment by HoplaGeiss** [comment]
Thanks! Elegant fix :)
