### ISSUE TITLE
[New Project] Combind tree-grid-directive & angular-ui-tree

### ISSUE THREAD

**Issue by thienhung1989** [angular-ui-tree/angular-ui-tree#434]
* Demo: http://thienhung1989.github.io/angular-tree-table/

* This product is the combination and optimization of 2: https://github.com/angular-ui-tree/angular-ui-tree (Drag2Drop) and https://github.com/khan4019/tree-grid-directive (Display Tree2Table).

Working with AngularJS.

Thanks @JimLiu and all.

**Comment by Voles** [comment]
@thienhung1989 looks nice! :-) Is this a personal experiment or are you working on a project which needs this?

**Comment by ernestopye** [comment]
That's really cool. I have a project that might actually benefit from something like this.

**Comment by thienhung1989** [comment]
Thanks @Voles & @enkodellc, I working on this project. Used to manage languages (English, Vietnam, ... ), permission,... and see also other details.
