### ISSUE TITLE
version bump?

### ISSUE THREAD

**Issue by honkskillet** [angular-ui-tree/angular-ui-tree#436]
In light of #411, the current version has gotten kind of confusing, especially given the reversion from 2.2 back to 2.15.  Can we consider a version bump to, say, 2.25 or 2.3?

**Comment by Voles** [comment]
Version [2.3.0](https://github.com/angular-ui-tree/angular-ui-tree/releases/tag/v2.3.0) has just ben released! Please take a look at the release notes.

**Comment by honkskillet** [comment]
Cool
