### ISSUE TITLE
Cannot read 'callback' of undefined

### ISSUE THREAD

**Issue by msvbg** [angular-ui-tree/angular-ui-tree#437]
Thanks for putting in the time to revive this great library. I've started getting errors out of nowhere that weren't appearing before, and I'm not sure how to resolve them. Whenever I'm dragging and dropping nodes in the tree, I get the following errors.

```
TypeError: Cannot read property 'dragStart' of undefined
    at angular-ui-tree.js:995

TypeError: Cannot read property 'beforeDrop' of undefined
    at angular-ui-tree.js:1183

TypeError: Cannot read property 'dropped' of undefined
    at angular-ui-tree.js:1194

TypeError: Cannot read property 'dragStop' of undefined
    at angular-ui-tree.js:1200
```

I have not defined these callbacks in my `ui-tree`, and defining them does not make the errors go away. My understanding of the library's internal workings is not strong enough to figure out how to debug this. Any help is greatly appreciated.

**Comment by Voles** [comment]
What version are you on? On the latest release (v2.3.0), `angular-ui-tree.js:995` contains `}, function (newVal) {`.

**Comment by Voles** [comment]
Please create a JSFiddle using the latest release so we can further investigate!
