### ISSUE TITLE
tags of older versions

### ISSUE THREAD

**Issue by ramigg** [angular-ui-tree/angular-ui-tree#438]
please don't delete older version tags. I had an issue when bower.json pointed to version 2.2.0 which doesn't exist anymore.

Thanks!

**Comment by vtmoren** [comment]
Can we add that tag back?  My Application is not working with the new update.

**Comment by Voles** [comment]
Re-added the [v2.2.0](https://github.com/angular-ui-tree/angular-ui-tree/releases/tag/v2.2.0) tag. Sorry for removing the previous one, I assumed it wasn't used. Lesson learned...
