### ISSUE TITLE
attribute empty-placeholder-enabled (or data-empty-placeholder-enabled) does not work

### ISSUE THREAD

**Issue by adambowen** [angular-ui-tree/angular-ui-tree#448]
Angular: 1.3.15
Browser: 5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) Safari/538.1
angular-ui-tree: 2.3.0

All of the following show the empty placeholder, when the documentation implies they shouldn't
```
	<div
		ui-tree
		ui-tree-nodes
		ng-model="emptyArray"
		data-empty-placeholder-enabled="false"></div>
	<div
		ui-tree
		ui-tree-nodes
		ng-model="emptyArray"
		data-empty-place-holder-enabled="false"></div>
	<div
		ui-tree
		ui-tree-nodes
		ng-model="emptyArray"
		empty-placeholder-enabled="false"></div>
	<div
		ui-tree
		ui-tree-nodes
		ng-model="emptyArray"
		empty-place-holder-enabled="false"></div>
```

There seem to be a number of problems with the implementation:
1. The documentation states that the the attribute is `data-empty-placeholder-enabled`, but the code refers to `attrs.emptyPlaceHolderEnabled`. This should be `attrs.emptyPlaceholderEnabled` if the documentation is correct, or `data-empty-place-holder-enabled` if the code is correct.
2. The code uses `typeof attrs.emptyPlaceHolderEnabled == "boolean"`, but this is a DOM attribute and therefore has the type "string".
3. `$scope.emptyPlaceHolderEnabled` is initialised to `true`, and tested in `resetEmptyElement`, but `resetEmptyElement` is only called when the length of the model changes, not when `emptyPlaceHolderEnabled`, so for an initially empty list the the placeholder is always shown.

**Comment by Voles** [comment]
See #450
