### ISSUE TITLE
A way to rename a node title?

### ISSUE THREAD

**Issue by pootzko** [angular-ui-tree/angular-ui-tree#456]
I've looked through the docs and issues but I wasn't able to find anything about this. Is there a way to rename a node? How was this intended to be handled from the user perspective? Thanks.

**Comment by andrewmclagan** [comment]
xEditable directive will help you out, search it on google.

**Comment by pootzko** [comment]
That's not what I meant. I meant is it supported by your directive by default. But I guess your reply answers that as well. Thanks.

Cheers

**Comment by andrewmclagan** [comment]
No problem, BTW its not my repo. cheers.
