### ISSUE TITLE
Example page broken

### ISSUE THREAD

**Issue by AquilaSagitta** [angular-ui-tree/angular-ui-tree#457]
Does this library actually work?

edit: Example page linked at the top of github repo (http://angular-ui-tree.github.io/website/)

The example page linked later on in the readme works fine

**Comment by OzzieOrca** [comment]
I noticed this too. http://jimliu.github.io/angular-ui-tree/ (which is referenced in the readme) works fine. Maybe update the website at the top of the repo?

**Comment by chino23** [comment]
The one in http://jimliu.github.io/angular-ui-tree/ works but it's using 2.0.13

**Comment by Voles** [comment]
@AquilaSagitta, @OzzieOrca, @chino23 the online website is updated with the new examples. It's not yet complete, but a good starting point.

See http://angular-ui-tree.github.io/angular-ui-tree

Feedback and PR's are welcome!

**Comment by OzzieOrca** [comment]
Should http://angular-ui-tree.github.io/website/ be taken down or fixed? I'm not sure if it is still linked anywhere.
