### ISSUE TITLE
Is it possible to increase the dropping area?

### ISSUE THREAD

**Issue by YouLu** [angular-ui-tree/angular-ui-tree#484]
Hi all,

I created two trees. Initially, tree 1 contains data, and tree 2 is empty. I will drag data from tree 1 to tree 2. My problem is tree 2's dropping area is very small, and I have to drop the node real carefully so that the node can be added in tree 2. Is there a way to increase the dropping area in tree 2?

Thanks,
Steven

**Comment by jacobscarter** [comment]
Closing this ticket, it is a duplicate of #465 which is open and should be addressed shortly
