### ISSUE TITLE
Dragging inside a div with a fixed height and overflow:scroll does not follow mouse

### ISSUE THREAD

**Issue by demetriusnunes** [angular-ui-tree/angular-ui-tree#49]
I have a draggable tree inside a modal. When the tree is longer than the fixed height of the modal, it creates a scrollbar inside de modal body div, as expected.

The problem is that when I try to drag some item beyond the modal div area, it does not trigger the scroll inside the modal body. Instead, it triggers the scroll of the whole page body.

**Comment by Voles** [comment]
@clementprevot any updates on this?

**Comment by tb9jen** [comment]
I am also hoping for a fix for this soon. Any updates?

**Comment by phw** [comment]
@Voles Any info on why this was closed? For me this still seems to be not working. Might also be the issue on #644

**Comment by jacobscarter** [comment]
Available in v2.21.1
