### ISSUE TITLE
Support for wiredep friendly enough.

### ISSUE THREAD

**Issue by zswang** [angular-ui-tree/angular-ui-tree#503]
Use the 「AngularJS Full-Stack generator」

https://github.com/DaftMonk/generator-angular-fullstack

-- package.json --
```json
  "dependencies": {
    。。。
    "wiredep": "~0.4.2",
    。。。
  },
```

### Repositorie

+ [wiredep](https://github.com/taptapship/wiredep)

### Base

-- index.html --

```html
<!-- bower:js -->
<!-- endbower -->
```

### Currently

-- bower.json --
```json
  "main": [
    "dist/angular-ui-tree.js",
    "dist/angular-ui-tree.min.js",
    "dist/angular-ui-tree.min.css"
  ],
```
`$ wiredep --dependencies -s index.html`

+ output:

```html
<!-- bower:js -->
<script src="../bower_components/angular/angular.js"></script>
<script src="../bower_components/angular-ui-tree/dist/angular-ui-tree.js"></script>
<script src="../bower_components/angular-ui-tree/dist/angular-ui-tree.min.js"></script>
<!-- endbower -->
```

### Perfect

-- bower.json --
```json
  "main": [
    "dist/angular-ui-tree.min.js",
    "dist/angular-ui-tree.min.css"
  ],
```

`$ wiredep --dependencies -s index.html`

+ output:

```html
<!-- bower:js -->
<script src="../bower_components/angular/angular.js"></script>
<script src="../bower_components/angular-ui-tree/dist/angular-ui-tree.min.js"></script>
<!-- endbower -->
```

Please consider whether to optimize.
Thanks

**Comment by doublemarked** [comment]
See #487

**Comment by Voles** [comment]
[v2.6.0](https://github.com/angular-ui-tree/angular-ui-tree/releases/tag/v2.6.0) has been released. Feedback is welcome!
