### ISSUE TITLE
is there dragover event

### ISSUE THREAD

**Issue by andela-omesanni** [angular-ui-tree/angular-ui-tree#520]
Hi,
I just wanted to find out if there is a dragover event. I am using angular material md-tabs and i want that if  I drag a certain li element over a particular, the md-tab will switch to the current one that something is being dragged over. The previous drag and drop plugin has this feature but the plug makes use of the native html5 drag and drop api and they have no support for mobile devices hence i am trying to now use angular-ui-tree.

I would appreciate if you guys had a dragover event. Thanks

**Comment by StefanCodes** [comment]
You can see the available events here: https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js

Specifically, you can implement 5 events in your tree config that relate to dragging a node:
* dragStart
* dragMove
* beforeDrop
* dropped
* dragStopped

One way this might work is to implement the dragMove callback, and check if the node is currently over another tab, and switch the tab if so. Note that the events only act on the node that's being dragged.

**Comment by tangorri** [comment]
I also would like to handler dropOver, because I looking to a way to allow drop on close folder ...
