### ISSUE TITLE
TypeError: $scope.$parentNodesScope.$modelValue.indexOf is not a function

### ISSUE THREAD

**Issue by ssivaprasad** [angular-ui-tree/angular-ui-tree#530]
Getting following error when I am  about to drag child node element
<b>
TypeError: $scope.$parentNodesScope.$modelValue.indexOf is not a function
 at Scope.$scope.index (angular-ui-tree.js:78)
    at Object.dragInfo (angular-ui-tree.js:1137)
    at link.dragStart (angular-ui-tree.js:627)
    at link.dragStartEvent (angular-ui-tree.js:926)
    at angular-ui-tree.js:963
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312
</b>
when looked into code in angular-ui-tree.js, it is like 
<b>
 $scope.index = function () {
          return $scope.$parentNodesScope.$modelValue.indexOf($scope.$modelValue);
 };
</b>

I am using Indexed array only.. But still why i am getting this? 
can any one help me plss?

**Comment by StefanCodes** [comment]
At a glance it sounds like $scope.$parentNodesScope.$modelValue is assigned to a value that is missing or has overridden the prototype of indexOf.

It's difficult to understand this problem out of context - can you create a JsFiddle or Plunkr and link it to this issue?

**Comment by selfinterest** [comment]
Not sure if this will help, but I had the same problem. The issue was that my top level model -- the one at the root of the tree -- was not an array, but a map. Once I realized that the root of the tree wasn't synonymous with the root level of the JSON document I was trying to represent in a tree, everything went fine.

**Comment by farantesrodrigues** [comment]
@ssivaprasad, I get the exact same error, did you find the problem ?
