### ISSUE TITLE
npm package ?

### ISSUE THREAD

**Issue by sdebacker** [angular-ui-tree/angular-ui-tree#535]
It should be great to make angular-ui-tree installable with npm. What do you think ?

**Comment by Voles** [comment]
What do we need to do in order to make it installable with NPM?

**Comment by sdebacker** [comment]
I never make a npm package, but here is some doc:

- https://quickleft.com/blog/creating-and-publishing-a-node-js-module
- https://docs.npmjs.com/getting-started/creating-node-modules
- https://docs.npmjs.com/misc/developers

**Comment by Voles** [comment]
I'm open for it, a PR is welcome!

**Comment by sdebacker** [comment]
ok, I will do it

**Comment by Voles** [comment]
Great, here's a link to your PR for future reference: #537

**Comment by AdamSelene** [comment]
Hi,
As @sdebacker suggested on #537, could you publish the module as-is on the npm registry (with a simple npm publish)? For us stuck with using artifactory from behind a corporate proxy (which means no github urls), that would be great.
Thanks a lot!

**Comment by Voles** [comment]
Done! See https://www.npmjs.com/package/angular-ui-tree

**Comment by AdamSelene** [comment]
Perfect, thanks :)

**Comment by kcaron-cst** [comment]
Can this be republished with new releases? Would be awesome for those that prefer not to use bower.

**Comment by Voles** [comment]
Done! https://www.npmjs.com/package/angular-ui-tree
