### ISSUE TITLE
Drop not working in IE10 on Windows 7

### ISSUE THREAD

**Issue by alanheppenstall** [angular-ui-tree/angular-ui-tree#55]
Viewing the demo at: http://jimliu.github.io/Angular-NestedSortable/

When I drag elements you can't seem to drop them into a different position - other elements aren't moving to clear space. Seems like it could be a CSS positioning issue.

Only seems to be happening in <IE10.

Thanks

**Comment by Chochek** [comment]
@JimLiu @clementprevot it's still not working in IE10.

**Comment by Voles** [comment]
Please create a JSFiddle using latest release (v2.3.0) explaining the issue so we can further investigate.
