### ISSUE TITLE
Dragging to bottom place doesn't seem to work

### ISSUE THREAD

**Issue by H-a-w-k** [angular-ui-tree/angular-ui-tree#552]
Dragging a system from 1. to last place works here:

<div class="container">
    <div class="row">
        <div class="col-lg-12" ui-tree="options">
            <ol ui-tree-nodes ng-model="entity.EnergySystems" data-type="EnergySystem">
                <li ng-repeat="system in entity.EnergySystems" ui-tree-node>
                    <div class="angular-ui-tree-handle">
                        <a href="" class="btn btn-danger btn-xs pull-right" data-nodrag ng-click="removeGroup(group)"><i class="glyphicon glyphicon-remove"></i></a>
                        <a href="" class="btn btn-primary btn-xs pull-right" data-nodrag ng-click="editGroup(group)"><i class="glyphicon glyphicon-pencil"></i></a>
                        <div>&nbsp;{{system.Name}}</div>
                    </div>
                    <ol ui-tree-nodes ng-model="system.EnergySystemPosts" data-type="{{system.Id}}">
                        <li ng-repeat="post in system.EnergySystemPosts" ui-tree-node>
                            <div class="angular-ui-tree-handle">
                                <a href="" class="btn btn-danger btn-xs pull-right" data-nodrag ng-click="removeCategory(group, category)"><i class="glyphicon glyphicon-remove"></i></a>
                                <div>
                                    &nbsp;{{post.Name}}
                                </div>
                            </div>
                        </li>
                    </ol>
                    <ol class="angular-ui-tree-nodes" data-nodrag>
                        <li class="angular-ui-tree-node">
                            <div class="angular-ui-tree-handle">
                                <form class="form-inline" role="form">
                                    <div class="form-group">
                                        <label class="sr-only" for="categoryName">Category name</label>
                                        <input type="text" class="form-control" ng-model="system.newCategoryName" placeholder="Category name">
                                    </div>
                                    <button type="submit" class="btn btn-default" ng-click="addCategory(group)">Add Category</button>
                                </form>
                            </div>
                        </li>
                    </ol>
                </li>
            </ol>
        </div>
    </div>
</div>

but not when the last tree nodes are removed like here:

<div class="container">
    <div class="row">
        <div class="col-lg-12" ui-tree="options">
            <ol ui-tree-nodes ng-model="entity.EnergySystems" data-type="EnergySystem">
                <li ng-repeat="system in entity.EnergySystems" ui-tree-node>
                    <div class="angular-ui-tree-handle">
                        <a href="" class="btn btn-danger btn-xs pull-right" data-nodrag ng-click="removeGroup(group)"><i class="glyphicon glyphicon-remove"></i></a>
                        <a href="" class="btn btn-primary btn-xs pull-right" data-nodrag ng-click="editGroup(group)"><i class="glyphicon glyphicon-pencil"></i></a>
                        <div>&nbsp;{{system.Name}}</div>
                    </div>
                    <ol ui-tree-nodes ng-model="system.EnergySystemPosts" data-type="{{system.Id}}">
                        <li ng-repeat="post in system.EnergySystemPosts" ui-tree-node>
                            <div class="angular-ui-tree-handle">
                                <a href="" class="btn btn-danger btn-xs pull-right" data-nodrag ng-click="removeCategory(group, category)"><i class="glyphicon glyphicon-remove"></i></a>
                                <div>
                                    &nbsp;{{post.Name}}
                                </div>
                            </div>
                        </li>
                    </ol>
                </li>
            </ol>
        </div>
    </div>
</div>

**Comment by zachlysobey** [comment]
Its not clear to me what your problem is. From your examples, `1.` is the root of the tree in both, and thus has no where to be dragged to. As far as I can tell, everything from [this demo](http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example) seems to be working properly.

**Comment by kotmatpockuh** [comment]
@zachlysobey  https://github.com/angular-ui-tree/angular-ui-tree/issues/564  seems the same...

**Comment by H-a-w-k** [comment]
Hey, sorry. I have been gone.
Oh I see I didn't copy paste well.
I solved the problem by adding a no-drag element at the bottom.
My problem was that I had nested draggable items, and I wasn't able to drag from first to last position on the outer ng-repeat. When I added a last invisible no-drag element it worked. I was however able to drag from last to first. 
Sorry for the inconvenience.

**Comment by kotmatpockuh** [comment]
@H-a-w-k  sorry, could you make a fiddle? With your demo-code?

**Comment by kotmatpockuh** [comment]
@H-a-w-k 
@zachlysobey 

also, seems that we need some code improvement...

**Comment by Voles** [comment]
Seems like this issue has been resolved by @H-a-w-k.

@kotmatpockuh if you have suggestions to improve the code, feel free to submit a PR or provide feedback!

**Comment by kotmatpockuh** [comment]
@Voles 
no, it isn't solved
i could make you an video...
