### ISSUE TITLE
Weird code

### ISSUE THREAD

**Issue by bronielsen** [angular-ui-tree/angular-ui-tree#559]
I stumbled over this code segment in the link function in the uiTreeNodes directive:
```javascript
ngModel.$render = function () {
    if (!ngModel.$modelValue || !angular.isArray(ngModel.$modelValue)) {
        scope.$modelValue = [];
    }
    scope.$modelValue = ngModel.$modelValue; // This will overwrite whatever happens above
};
```

As I see it the scope.$modelValue = [] assignment has no effect since it is overwritten right after.

Am I missing something here?

**Comment by StefanCodes** [comment]
Looks like that code was refactored and that statement became redundant: https://github.com/angular-ui-tree/angular-ui-tree/commit/443e5fad7e84643773ed97059227da2e9392f75f#diff-569690a868827f658f34e4f67dc84ae5. Probably a simple oversight.

I don't think you're missing anything - that block of code can probably be removed.

**Comment by Voles** [comment]
You're right. I've removed that condition. Thanks!
