### ISSUE TITLE
Dragging: Horizontal movement not recognized

### ISSUE THREAD

**Issue by SvenJunga** [angular-ui-tree/angular-ui-tree#562]
A tree does not accept a node that is dragged with almost only horizontal movement. Only vertical movement seems to be recognized. See the following example:

![example.gif](https://cloud.githubusercontent.com/assets/12759080/9342168/982605c4-45fa-11e5-8df8-ecfb4b912041.gif)

Tested with Chromium for Windows and Mac.

**Comment by SvenJunga** [comment]
Finding the piece of code that causes this behavior isn't that hard. It's the `dragMove`-Method of the uiTreeNode. There's a condition `if (!pos.dirAx)` around line 315 that prevents the tree from accepting the node. But I haven't found a non hacky way of changing this yet. 
This somehow works for me but I think it could break other setups: https://github.com/SvenJunga/angular-ui-tree-touch/commit/e12932b091f6650cb86ec7d9e89d5f3f2b1c1618#diff-2bd42e539aeba5277f65f2599dfc0338

**Comment by nulltone** [comment]
+1. I'm having the same problem.

**Comment by jacobscarter** [comment]
+1

**Comment by zachlysobey** [comment]
for reference, here the code  that @SvenJunga metioned [above](https://github.com/angular-ui-tree/angular-ui-tree/issues/562#issuecomment-132492240) *in context*
> `if (!pos.dirAx)`) 

[*uiTreeNode.js#L377*](https://github.com/angular-ui-tree/angular-ui-tree/blob/ee3c61ca31ac6f3ed34d3f8fff0daeab94115906/source/directives/uiTreeNode.js#L377)

**Comment by danielforsberg** [comment]
+1

**Comment by SvenJunga** [comment]
@zachlysobey have you found a better solution to this than my proposed hack? This seems to be a annoying bug to many people.

**Comment by zachlysobey** [comment]
@SvenJunga nope, haven't even tried or looked into it; Just tracked down that line of code in the hopes that it might make it a little easier for someone to dig into this and perhaps submit a PR.

**Comment by noherczeg** [comment]
+1

**Comment by jacobscarter** [comment]
I think I have a fix for this I will implement soon, horizontal movement is not recognized because it is checking to see if you are moving a node within its own tree to "un-nest" it.  I will add a bit that stops checking for that as soon as you leave the origin tree, so horizontal movement beyond that will be recognized as a node traveling.  Not sure if this makes sense but I'll have the fix soon and can show via demo rather than just explaining it.

**Comment by jacobscarter** [comment]
The fix I implemented here now uses tree IDs to determine if you are re-adjusting nestings rather than pixel measurements on the screen.

**Comment by jacobscarter** [comment]
PR [#824](https://github.com/angular-ui-tree/angular-ui-tree/pull/824)

**Comment by jacobscarter** [comment]
Fix available in v2.22.0
