### ISSUE TITLE
bower package name contains spaces and cannot be html linked

### ISSUE THREAD

**Issue by itsjustcon** [angular-ui-tree/angular-ui-tree#567]
I guess no one around here uses bower because the `bower.json` file currently lists the package name as `"Angular JS UI Tree"` making the advised HTML drop-in (from the README):
```html
<script type="text/javascript" src="bower_components/angular-ui-tree/dist/angular-ui-tree.js"></script>
```
...which returns a ***404*** b/c that directory doesn't actually exist so you actually have to do:
```html
<script type="text/javascript" src="bower_components/Angular JS UI Tree/dist/angular-ui-tree.js"></script>
```
...to get it working, but many browsers treat this as a malformed link.

My temporary work-around is to do this in my own project's `bower.json` to properly link the package under the `angular-ui-tree` directory:
```json
{
  "dependencies": {
    "angular-ui-tree": "angular-ui-tree#~2.8.0"
  }
}
```

The real solution here is just to change this repo's `bower.json` to:
```json
{
  "name": "angular-ui-tree"
}
```

**Comment by Voles** [comment]
The documentation says installing using Bower can be done using `$ bower install angular-ui-tree`. Bower will use `git://github.com/JimLiu/angular-ui-tree.git`, which redirects to the current repository (`https://github.com/angular-ui-tree/angular-ui-tree`).

Doing so, I don't see references to `/Angular JS UI Tree` in any URL. I'm curious how you got those links?

**Comment by Voles** [comment]
Your suggestion makes sense, as `Angular UI Tree` is an invalid [Bower package name](http://bower.io/docs/creating-packages/#name).
