### ISSUE TITLE
Recursive rendering based on nested objects, not 'children' arrays

### ISSUE THREAD

**Issue by afedulov** [angular-ui-tree/angular-ui-tree#571]
I need to present data serialized from MongoDB objects. This data does not have predefined ```{'name': 'SomeKey', 'value': 'someValue', 'children': [{'name': 'SomeOtherKey', 'value': 'someOtherValue'}]} ``` structure but looks just like a nested hierarchy of objects ``` {'key1': 'someValue1', 'key2': {'key3':'someValue2'}, 'key4': ['arrayValue1', arrayValue2]}```. My questions are
1) would modifying angular-ui-tree for achieving this be something that could be done with reasonable amount of effort, or would you estimate this change as too complex/contradicting with angulajs internals (for instance ng-repeat)
2) If it is doable, I would appreciate any hints on where to start. I do not need drag-drop, addition, deletion functionality: just rendering and filtering.

**Comment by Voles** [comment]
Please ask for ideas in our chat room, see https://gitter.im/angular-ui-tree/angular-ui-tree

**Comment by afedulov** [comment]
I did a week ago. I would appreciate your comments on this.
