### ISSUE TITLE
dragThreshold is unused

### ISSUE THREAD

**Issue by StefanCodes** [angular-ui-tree/angular-ui-tree#575]
TreeConfig has a property named `dragThreshold` that is presumably supposed to represent the number of pixels a draggable node has to be dragged before the UI "goes into drag mode" (apply drag CSS, show placeholder, etc). This property is currently unused in the control's actual implementation.

This should be wired up and used - it's a useful option to let users configure.

I'm not sure where the best place is to fix this - I imagine somewhere towards the top of `dragStart()`.

**Comment by jacobscarter** [comment]
I'll update this on my next PR
