### ISSUE TITLE
Create TypeScript typings for angular-ui-tree

### ISSUE THREAD

**Issue by StefanCodes** [angular-ui-tree/angular-ui-tree#577]
I'm working in TypeScript and currently have no type safety when writing code using angular-ui-tree. Create a typings file (.d.ts) for the control and submit it to the [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) repository.

**Comment by matijagrcic** [comment]
This was added with borisyankov/DefinitelyTyped#5540 with borisyankov/DefinitelyTyped@cf1f872
