### ISSUE TITLE
'accept' is never called on iOS 8.4.1

### ISSUE THREAD

**Issue by SvenJunga** [angular-ui-tree/angular-ui-tree#585]
I recently updated my iPad at work to iOS 8.4.1 to find out that the accept-method isn't called anymore when dragging. `document.elementFromPoint()` seems to be broken in iOS 8.4.1 when the `display`-attribute of the dragged element is changed right before the call. See this thread for reference: https://github.com/bevacqua/dragula/issues/164

I can fix this for mobile Safari, desktop-Chromium and desktop-IE with the following simple change: https://github.com/SvenJunga/angular-ui-tree-touch/commit/da1d31811acf00bbeb3461a6da0f44863c6f03e2#diff-2bd42e539aeba5277f65f2599dfc0338
But the comment above concerning IE and CSS-pointer-events makes me feel uncomfortable. Anyone?

**Comment by Voles** [comment]
@ppuleo do you know which version of IE this is about?

I don't think we can just remove the fix made in the current code. It provides support for <IE11.
For browser support, see http://caniuse.com/#feat=pointer-events

**Comment by ppuleo** [comment]
Hi @Voles, I'm not familiar with that section of the code but since IE11 and later correctly support pointer events, it might be a reasonable time to drop support for <IE11 with a major version change. Or maybe we could look into browser detection and target the fix.

**Comment by SvenJunga** [comment]
Works again with iOS 9.
