### ISSUE TITLE
Working example inside a directive?

### ISSUE THREAD

**Issue by kcaron-cst** [angular-ui-tree/angular-ui-tree#588]
I am having trouble getting toggle to work in a directive pattern. Below is a plunker of a simplified example of what I am trying to do.

http://plnkr.co/edit/of5CMctQ8WzQgA5oycPy?p=preview

The only change I made to the source file is to add an alert to the toggle function to demonstrate that the directive is indeed sending toggle to the right scope, and changing `collapsed`

Not sure what I am missing, and help would be appreciated.

**Comment by Voles** [comment]
I'm not sure what you are trying to accomplish here? It looks like the tree is rendered correctly.

**Comment by kcaron-cst** [comment]
I am trying to get the sub items to toggle visibility. Maybe I am misunderstanding if the toggle function only handles switching a variable. If I manually add `ng-class="{'angular-ui-tree-hidden': collapsed}"` to the subitems `li` it behaves as I'd expect, but that feels I'm taking an extra step.

**Comment by Voles** [comment]
In the online demo, the sub-nodes are also hidden by adding the `hidden` class to collapsed nodes.
`<ol ui-tree-nodes="" ng-model="node.nodes" ng-class="{hidden: collapsed}">`

The `hidden` class is part of Bootstrap, but you can easily style it yourself. This is what Bootstrap uses:
````
display: none!important;
visibility: hidden!important;
````
