### ISSUE TITLE
Save expand/collapse state of all nodes?

### ISSUE THREAD

**Issue by hzektser** [angular-ui-tree/angular-ui-tree#591]
Is there any way to save/load the expand/collapse state of all nodes? I've had no luck finding a way to do it..

**Comment by forcewill** [comment]
You could use a service storing the state of each node, and then just expand/collapse according

**Comment by ernestopye** [comment]
Hey @forcewill, do you know how to get a reference to the root node? The solution sounds simple enough, but I'm not sure how to access the root nodeScope in order to traverse and tree and set the "collapsed" property as needed.
