### ISSUE TITLE
if the tree is empty, how can i add a new node by program?

### ISSUE THREAD

**Issue by subjectwa** [angular-ui-tree/angular-ui-tree#593]
I can use the follow code to add a node to the tree on 1-level if the tree is not empty
<pre><code>
var newData = {title:'test'};
var uiTreeScope = angular.element('[ui-tree]').scope();
if (uiTreeScope.$nodesScope.$modelValue.length > 0)
    uiTreeScope.$nodesScope.$modelValue.push(newData);
</code></pre>
but if the tree is empty,it will get this error:
<pre><code>
uiTreeScope.$nodesScope.$modelValue is undefined
</code></pre>
then i try the follow
<pre><code>
if(angular.isUndefined(uiTreeScope.$nodesScope.$modelValue)) {
   uiTreeScope.$nodesScope.$modelValue = [];
   uiTreeScope.$nodesScope.insertNode(0,newData);
}
</code></pre>
there is no error,but the tree isn't show up,so what's the solution?

**Comment by SvenJunga** [comment]
Have you tried adding your data to the ng-model-value bound to the `ui-tree-nodes`?

Let's say you got the following template:
```html
<div ui-tree>
  <ol ui-tree-nodes="" ng-model="list">
    <li ng-repeat="item in list" ui-tree-node>
      <div ui-tree-handle>
        {{item.title}}
      </div>
      <ol ui-tree-nodes="" ng-model="item.items">
        <li ng-repeat="subItem in item.items" ui-tree-node>
          <div ui-tree-handle>
            {{subItem.title}}
          </div>
        </li>
      </ol>
    </li>
  </ol>
</div>
```

Then just add your data to `list`

**Comment by subjectwa** [comment]
it works,thks!
