### ISSUE TITLE
"dropped" callback still trigger even if "accept" is false

### ISSUE THREAD

**Issue by cherihung** [angular-ui-tree/angular-ui-tree#594]
I'm implementing a custom'accept callback method. And noticing that even if the accept returns false, further callbacks are still triggered, namely the "dropped" callback.

Is this the intended design? Or am I doing something wrong with my method?

**Comment by SvenJunga** [comment]
This doesn't happen here. So I don't think it's intended. Can you provide sample code?

**Comment by cherihung** [comment]
I recently upgraded to 2.9.0 and this doesn't occur anymore. (yay)
previously, I was using 2.5.0 and that's where I saw it - when implementing my own "accept" callback, even with a sole and simple ```return false```, 'dropped' was being triggered.
can consider this closed though since latest version works.
