### ISSUE TITLE
How to drag and drop any object into the tree 

### ISSUE THREAD

**Issue by nicklasb** [angular-ui-tree/angular-ui-tree#601]
Hi, 
I am looking for a way to make angular-ui-tree to accept items from other sources than angular-ui-tree-instances. I am not sure why It doesn't react, the callbacks.accept isn't even called.

Any ideas? Of course I realize that I will have to create something that angular-ui-tree accepts as a source.

**Comment by maliseenko** [comment]
Hi nicklasb,

Did you found any solution? We are looking on same functionality. If you found something, please share with us.

**Comment by nicklasb** [comment]
Hi @maliseenko,
No, not yet. I am just now looking at the UiTreeHelper.eventObj(e), but I am honestly not sure how it works. It is quite extensive, the drag'n drop implementation of UI-tree.

**Comment by nicklasb** [comment]
Hm. It seems like the tree has some internal functionality for this. It has an internal variable called dragElm that is set in dragStart and then referred to in dragStop.

I am not sure how to get around that. Not sure why that isn't passed by the dragevent.dataTransfer.get/setData instead, then it could be provided from outside.

**Comment by nicklasb** [comment]
To basically somehow break into the trees internal scope and set it seems ugly.

**Comment by nicklasb** [comment]
However it seems like it is possible to drag'n drop between trees, I don't get that really.

**Comment by nicklasb** [comment]
Actually, there seem to be a small bug in dragStop. 
It calls bindDrag each time something is dropped, which means that after having dragged and dropped something 10 times, it is called 10 times after each drop. Which seems a bit unnecessary.
Or at least that seems to be the issue.

**Comment by nicklasb** [comment]
Just mentioning that I resolved this one by making the outside source a tree as well. 
However, I do not think that that should have been necessary.
Closing, at least for my part.
