### ISSUE TITLE
Get ui-tree-node of a node 

### ISSUE THREAD

**Issue by cgarnier** [angular-ui-tree/angular-ui-tree#613]
How i m supposed to collapse a node from its model?

https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js#L48

this watcher just doesnt work.

**Comment by Voles** [comment]
Take a look at our basic example, which contains an example of expanding / collapsing a node.

View: https://github.com/angular-ui-tree/angular-ui-tree/blob/master/examples/views/basic-example.html#L4
Controller: https://github.com/angular-ui-tree/angular-ui-tree/blob/master/examples/js/basic-example.js#L10

**Comment by cgarnier** [comment]
I dont want to use a scope to collapse an element.
