### ISSUE TITLE
Incompatibility with angular-ui bootstrap modal

### ISSUE THREAD

**Issue by cdaguerre** [angular-ui-tree/angular-ui-tree#615]
Any escape key `keydown` event listener bound above the document body is prevented by these two lines: 
- https://github.com/angular-ui-tree/angular-ui-tree/blob/master/dist/angular-ui-tree.js#L1007
- https://github.com/angular-ui-tree/angular-ui-tree/blob/master/dist/angular-ui-tree.js#L917

For instance, the escape key functionaility of angular UI bootstrap's modal is always prevented.
Binding to `$document` rather than `$document.body` should fix the problem.
Shall I make a PR?

**Comment by StefanCodes** [comment]
@cdaguerre, was this problem fixed by https://github.com/angular-ui-tree/angular-ui-tree/pull/612? That has been merged but is not yet part of an official release.

**Comment by cdaguerre** [comment]
@StefanCodes No, but PR #636 does ;)
