### ISSUE TITLE
Plugins don't work

### ISSUE THREAD

**Issue by LeachBogdan** [angular-ui-tree/angular-ui-tree#617]
I'm pretty sure I did everything according to the guide. Included all the necessary files from the release version (angular-gantt.js/css, angular-gantt-plugins.js/css) added the modules to my app's dependencies, added the elements to the template 

```html
<div gantt data="projectData">
              <gantt-tree></gantt-tree>
</div>
````

I don't get any errors whatsoever. I put a log inside the link function of the plugin's directive and it just doesn't run.

I moved the movable element outside of the gantt just to see if the module is recognized, and i get the expected "controller required" error so the module is registered properly.

The gantt is displayed properly with my test data or the data from the demo but none of the plugins are activated. I've run out of things to try.

**Comment by Voles** [comment]
[Angular Gantt](https://github.com/angular-gantt/angular-gantt) is not related to the UI Tree component.
