### ISSUE TITLE
Getting strange error with version 2.9.0

### ISSUE THREAD

**Issue by stripathix** [angular-ui-tree/angular-ui-tree#641]
My tree is working perfectly fine. But server is getting too many errors log due to this strange error.

 Error Message : [$compile:ctreq] Controller 'uiTreeNodes', required by directive 'uiTreeNode', can't be found! 
http://errors.angularjs.org/1.4.6/$compile/ctreq?p0=uiTreeNodes&p1=uiTreeNode 

Does anybody face same issue.
I am using IE9 :-( .

**Comment by StefanCodes** [comment]
Can you show an example of this in a plunk/fiddle? Do you see the same issues in that browser on the demo page (http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example) ?

**Comment by stripathix** [comment]
Hard to reproduce my side. Just getting so many errors reported on server when end user uses application.

**Comment by Voles** [comment]
@stripathix it's quite difficult for us to investigate without further information. I'm closing this issue for now. Please reopen in case you are able to gather more information.
