### ISSUE TITLE
drag and drop event

### ISSUE THREAD

**Issue by HoplaGeiss** [angular-ui-tree/angular-ui-tree#662]
Is it possible to detect in the beforeDrag callback if the drag and drop is initiated by a left click or a right click ?

**Comment by StefanCodes** [comment]
I don't think that's currently possible - the callbacks only receive a `dragEventArgs`, which doesn't include the original event.

It's pretty trivial to add the original event as a parameter to the callbacks. I'm curious, though, how you're enabling dragging with a right-click? It looks like the ui-tree source code currently disables right click dragging entirely.

**Comment by HoplaGeiss** [comment]
Can you explain me how you would add the original event as a parameter to the callback ?

I created a custom directive to ignore the default behavior on a right click

```
    function link(scope, el){
      el.bind("contextmenu", function (e) {
        e.preventDefault();
      });
    }
```

I use it like this:

  <script type="text/ng-template" id="items_renderer.html">
    <div right-click>
      <div ui-tree-handle>
      ....
      </div>
    </div>
</script>

**Comment by StefanCodes** [comment]
Sure. This would require a PR to modify ui-tree, but if you just want to play around with your local copy for the moment:

https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js#L415
This line invokes the `beforeDrop` callback:
`scope.$treeScope.$callbacks.beforeDrop(dragInfo.eventArgs(elements, pos));`

To add the original event, change this to:
`scope.$treeScope.$callbacks.beforeDrop(dragInfo.eventArgs(elements, pos), e);`

Then in your own code, you'd implement the `beforeDrop` callback and get both parameters:
```
$scope.treeOptions = {
  beforeDrop : function (dragArgs,e) {
    // e is a MouseEvent
  }
}
```

Note also that you're going to have to fight this code in the same directive: https://github.com/angular-ui-tree/angular-ui-tree/blob/master/source/directives/uiTreeNode.js#L60
```
if (!hasTouch && (e.button == 2 || e.which == 3)) {
  // disable right click
  return;
}
```

For your test code you can just remove that block.

**Comment by HoplaGeiss** [comment]
thanks mate! Very helpful
