### ISSUE TITLE
disabling angular's debug mode causes drag to fail

### ISSUE THREAD

**Issue by giladv** [angular-ui-tree/angular-ui-tree#667]
disabling angular's debug mode is the right way to go on production for performance boost.
https://docs.angularjs.org/guide/production

the problem is that element.scope() does not work without the debug mode and ui-tree is dependent on it for the drag to work. 
as a result this plugin is not usable on production at the moment (unless you don't care about disabling debug mode)

please fix this, otherwise this thing is perfect for me
thanks!

**Comment by Voles** [comment]
We're working on this. For updates, see #648 Feedback is welcome!

**Comment by giladv** [comment]
oh great. though it might be a good idea to post a fair warning on this somewhere (unless i missed it)
thanks @Voles :)
