### ISSUE TITLE
2.11.0 introduces a memory leak

### ISSUE THREAD

**Issue by dani3l** [angular-ui-tree/angular-ui-tree#670]
Hi guys
I've just updated to latest version and noticed that it cuases a memory leak while dragging and dropping nodes.

This doesn't happen with 2.10.0.

**Comment by Voles** [comment]
v2.12.0 has been released. Can you update and check if you still encounter memory issues?

**Comment by dani3l** [comment]
I've checked and seems like it was fixed. Thanks!
