### ISSUE TITLE
Disconnect Trees

### ISSUE THREAD

**Issue by dowanx** [angular-ui-tree/angular-ui-tree#675]
Is there any way to disconnect trees so nodes can't be dragged or dropped in the other tree while still allowing nodes to be dragged and dropped within the tree they originate from?

**Comment by StefanCodes** [comment]
You should be able to accomplish this by implementing the `accept` callback in your tree(s). In the event handler, you can inspect the `treeScope` of the source and destination nodes, and if they differ (different trees), return false to prevent the drop.

**Comment by dowanx** [comment]
Wow worked great!  Thanks for the quick and very helpful response!  Here is the code I did just in case anyone else needs it.

accept: function(sourceNodeScope, destNodesScope, destIndex) {
               if (sourceNodeScope.$treeScope != destNodesScope.$treeScope) {
                  return false;
               }else{
                  return true;
               }
            }

**Comment by StefanCodes** [comment]
Great!

**Comment by mattjanssen** [comment]
Thanks for documenting this. I had the same problem for a while. Here's the shortened return line I used:

`return sourceNodeScope.$treeScope === destNodesScope.$treeScope;`

And just for some search juice: two multiple separate different trees disable dragging between
