### ISSUE TITLE
Angular-ui-tree and multiselection of nodes

### ISSUE THREAD

**Issue by klorgouilloux** [angular-ui-tree/angular-ui-tree#689]
Hi, 

my company started a new project and we decided to include the angular-ui-tree. We think that ui-tree is a very useful feature and is pretty simple to use.
But one of our need is to do multiselection of nodes. We saw that the multiselection was added in the history of ui-tree, but then we saw that a revert was done and we wonder why.

So is it possible to have help for our need ? 

Thanks,

Kevin

**Comment by Voles** [comment]
As discussed via email, I would be happy to review a PR with this functionality. I would like to focus on adding tests myself for the moment.
