### ISSUE TITLE
mouseleave drag cancel not working in chrome

### ISSUE THREAD

**Issue by CalvinFernandez** [angular-ui-tree/angular-ui-tree#691]
Mouse leave cancels the drag event in FF but not in chrome. Also, why does mouse leave cancel the drag? It's pretty disorienting for users imo.

**Comment by StefanCodes** [comment]
@CalvinFernandez I think this inconsistency was resolved in https://github.com/angular-ui-tree/angular-ui-tree/pull/648 (2.15.0). Can you give it a try and reopen this issue if you're still having problems?
