### ISSUE TITLE
How to drop node when parent node is collapsed?

### ISSUE THREAD

**Issue by bb005070** [angular-ui-tree/angular-ui-tree#693]
Hi Team,

Thanks for the great directive.

I need small help i.e. i have two trees. I can able to drag from tree1 to tree2 when parent node is expanded. Now I am unable drop child node when parent node is collapsed. Please help me on this issue.
Sample code would be more help.
Thanks in advance.

**Comment by Voles** [comment]
I've worked on expanding a collapsed node on hovering. See #539. Does that work for you?

**Comment by bb005070** [comment]
Thanks for the reply Voles ... But it doesn't work...
If i can get parent on which child was dropped it will help...

To be clear if child1 is dropped on parent 1 , is there way to get parent 1?

**Comment by geraldpereira** [comment]
I found a workaround: 

Simply add a treeController.expandOnMouseHover($event, this)

**Comment by burakkilic** [comment]
+1. @Voles when it will be available in bower?

**Comment by jacobscarter** [comment]
expand on hover is now a feature in this project
