### ISSUE TITLE
Jumpy placeholder issue in PR #648 (2.15.0)

### ISSUE THREAD

**Issue by robwalkerco** [angular-ui-tree/angular-ui-tree#705]
Nice work on PR #648, however, when I use 2.15.0 I have an issue when dragging sub-folders as can be seen in the gif below. Top level folders are no effected.

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6524830/12660731/2278538e-c60d-11e5-92bb-7c02f46c2acf.gif)

2.14.0 works fine.

The example page does not seem to be effected, and I'm not sure what is causing the issue.

Have you seen anything similar before, or know what may be causing it? Thanks for your help.

**Comment by Voles** [comment]
Thanks for reporting. The v2.15.0 release contains a single change, but with quite some impact. It removes the `scope()` dependency. This allows disabling the `debugInfo()` for your Angular application.

I guess it has to do with the whitespace arount the list items. Can you create a jsFiddle so we can further inspect what's going on here?

**Comment by burakkilic** [comment]
Same for me. 
![8zal7204du](https://cloud.githubusercontent.com/assets/123382/12754866/a678816a-c9d5-11e5-8d57-c50b2922b95a.gif)

**Comment by burakkilic** [comment]
I cannot drop the row in 2.15.0. I can drop in 2.14.0 but the placeholder is not shown.

**Comment by anthwinter** [comment]
The problem explained by @robwalkerco in this issue was caused by placing the `ui-tree-handle` alongside the `ui-tree-node`, instead of placing a separate element inside the ui-tree-node that contained ui-tree-node.

@robwalkerco did you want to close this issue? I'm unable to.

Problem:
```
<ul ui-tree-nodes>
  <li ui-tree-node ui-tree-handle>
    <div>Folder Name</div>
    <ul ui-tree-nodes>
      ...
    </ul>
  </li>
</ul>
```

Resolution:
```
<ul ui-tree-nodes>
  <li ui-tree-node>
    <div ui-tree-handle>Folder Name</div>
    <ul ui-tree-nodes>
      ...
    </ul>
  </li>
</ul>
```

**Comment by robwalkerco** [comment]
Thanks @anthwinter
