### ISSUE TITLE
added/inserted callback

### ISSUE THREAD

**Issue by gkTim** [angular-ui-tree/angular-ui-tree#706]
I need to have a possibility to get the html element of the lastest inserted node.
I see no possibility to get this currently. (Correct me if I'm wrong).

Would it be a possibility to add a added or inserted callback to handle these things?
I mean there is also a removed callback so why not an added callback.

I could try my luck and implement it if you wish and make a pull request.

**Comment by zachlysobey** [comment]
By inserted do you mean you're adding something to the tree model? Or just dropping an existing node? In both cases I can think of potential workarounds to get at the element...

**Comment by gkTim** [comment]
Im adding a node to the tree model.

**Comment by gkTim** [comment]
Here a solution to get the last node on the tree:
http://stackoverflow.com/questions/35101583/angular-ui-tree-how-to-get-html-element-of-last-added-node

**Comment by zachlysobey** [comment]
Hey @gkTim... sorry didn't mean to not respond. You were able to get this to work I hope?

**Comment by gkTim** [comment]
Yeah it's working now. Thanks

**Comment by thienedits** [comment]
@gkTim How did you get the delete to work on the newly added item? Doesn't seem to delete correctly

**Comment by gkTim** [comment]
Hi,

here is my deletion code:

```
  /**
   *
   * Removes recursively a node from the given treeArray with the given id.
   *
   * @param id {number} - tree node id.
   * @param treeArray {array} - array of tree nodes.
   *
   */
  removeNode(id, treeArray) {
    treeArray.forEach((item, i) => {
      if (item.id == id) {
        treeArray.splice(i, 1);
      }

      if (
        treeArray[i] &&
        treeArray[i].children &&
        treeArray[i].children.length > 0
      ) {
        this.removeNode(id, treeArray[i].children);
      }
    });
  }

  /**
   *
   * Function which is called from the UI to remove the selected node in the tree.
   *
   * @param node {TreeNode} - Node which should get removed.
   *
   */
  deleteNode(node) {
    this.removeNode(node.id, this.treeNodes);

    this.tree.treeModel.update();
  }
```
