### ISSUE TITLE
Can't drop node to empty connected tree

### ISSUE THREAD

**Issue by PSkierniewski** [angular-ui-tree/angular-ui-tree#707]
Hi, in v2.15.0 release, node can't be dropped to empty connected tree

Steps to reproduce:

1. Go to connected trees demo page http://angular-ui-tree.github.io/angular-ui-tree/#/connected-trees
2. Remove all nodes from **Tree 2**
3. Try to drop node form **Tree 1** to **Tree 2**

It works on v2.14.0 release - tested on Chrome and Firefox

**Comment by zachlysobey** [comment]
Yup, happening for me too.
(@Voles: good example of why I need to get my act together and finish all that e2e-test stuff)

**Comment by burakkilic** [comment]
+1

**Comment by austinbourdier** [comment]
+1

**Comment by austinbourdier** [comment]
Been trying to work around this for awhile. no luck.

**Comment by zachlysobey** [comment]
You can workaround by using v2.14 until there is an official fix ;)

**Comment by Khamull** [comment]
+1

**Comment by nishantsamant** [comment]
Any luck?

**Comment by danielforsberg** [comment]
+1

**Comment by rachelizv** [comment]
+1

**Comment by rachelizv** [comment]
does anyone pls post an example with v2.14 that works?

**Comment by burakkilic** [comment]
+1

**Comment by ErgoSoftUK** [comment]
I'm new to this component (and angular!) and I've been trying to get it to work (v2.15) and got this far.  Anyone confirm this fixes their issue too?

[ui-tree-fix.txt](https://github.com/angular-ui-tree/angular-ui-tree/files/165017/ui-tree-fix.txt)

**Comment by frankpaap** [comment]
For now I removed 

>  /*if (!targetNode) {
                    return;
                  }*/
On line 936 and it works for now...

**Comment by publicroot** [comment]
@ErgoSoftUk: Very good job. Thank you, saved my day.

**Comment by guilhermepatriarca** [comment]
@ErgoSoftUK :)

**Comment by ErgoSoftUK** [comment]
Glad it worked for you guys.  I did submit a pull request but someone said it didn't work for them.
https://github.com/angular-ui-tree/angular-ui-tree/pull/738

**Comment by nishantsamant** [comment]
@ErgoSoftUK  : This issue still exists. I tried this code but I can be able to drop child only once on the empty parent node. When I am trying for second time, it's failing.

Need ASAP help.

**Comment by nishantsamant** [comment]
@frankpaap This issue still exists. I tried this code but I can be able to drop child only once on the empty parent node. When I am trying for second time, it's failing. Need help ASAP

**Comment by ErgoSoftUK** [comment]
My tree looks like this...

`<div ui-tree id="report-tree">
    <ol ui-tree-nodes ng-model="reportCtrl.reportContent">
        <li ng-repeat="node in reportCtrl.reportContent" ui-tree-node ng-include="'report_template.html'">
        </li>
    </ol>
</div>`

I've attached the compiled version with the fixes...
[angular-ui-tree-withFix.txt](https://github.com/angular-ui-tree/angular-ui-tree/files/220872/angular-ui-tree-withFix.txt)

And also overridden some of the CSS...
[ui-tree-extensions.txt](https://github.com/angular-ui-tree/angular-ui-tree/files/220890/ui-tree-extensions.txt)

**Comment by nicklasb** [comment]
I am not sure, are any of the suggestions here a consistent fix? If so, can someone make a PR?

**Comment by ErgoSoftUK** [comment]
@nicklasb There already is a pull request, 
https://github.com/angular-ui-tree/angular-ui-tree/pull/738

**Comment by SMERKY** [comment]
+1 - Our team has coded a work around to add a dummy object if the tree node is empty, but it is not the cleanest solution

**Comment by Smolations** [comment]
+1

After a year of implementing this library, we are still unable to turn of angular debug info in production. My excitement for the v.2.15.0 release which solves the problem quickly turned into frustration due to this particular issue.  😖

**Comment by SMERKY** [comment]
@smolations - We have been able to switch off angular debug info with this library in production. Are you sure you have updated to the latest version or another library is not causing the issue?

**Comment by Smolations** [comment]
@SMERKY I am definitely using the latest version of this library. We are running Angular 1.5.6. We have the placeholder option set to true so we can see the drop zone. When the tree is empty, I am unable to drop a new node. If at least one node is present, dropping works as expected.

**Comment by SMERKY** [comment]
@Smolations - These are two seperate issues. Not being able to drag into an empty tree is a bug with the library whether you have angular debug on or not. It seems the library is running fine with angular debug off, but you are experiencing the same bug as the rest of us. Hopefully it gets fixed in the next version..

**Comment by Smolations** [comment]
@SMERKY Sorry, I should probably clarify. Turning angular debug off has been impossible up until the most recent release of this library (2.15.0). So in order to turn debug info off, I _must_ install that release. The current version my team is using is 2.7.0. At that version, the bug to drag into an empty tree is non-existent. It broke some time between 2.7.0 and the current release. So, while my original problem was that the library was completely non-functional when turning debug info off, my new problem appears to be this bug when installing the newest release, which _would_ allow me to turn off debug info. Does that make a bit more sense?

**Comment by StefanCodes** [comment]
@Smolations - I merged a PR that addressed dragging into an empty tree and released it with 2.16 - can you give that build a try and see if it resolves all your issues?

**Comment by Smolations** [comment]
@StefanCodes Huzzah! After installing 2.16.0 my app is working as expected again! I will get this change into production (_without_ debug info!) and keep a close eye on feedback to see if there are any further issues. Thank you so much for helping get the fix out!  😄 👍

**Comment by StefanCodes** [comment]
Excellent! Closing this issue - anyone following please reopen if you're still having issues.

**Comment by ThomasVD88** [comment]
I've added is a bower webjar to webjars.org

**Comment by Bakirelived** [comment]
Is the demo using an outdated version? I have the same problem reported on the first post, on the demo page. Also, I've updated my version to the latest(2.17), and I can't drop into an empty tree.

**Comment by urza710** [comment]
Demo fail with 2.17.
This issue has not been fix

**Comment by DoobleD** [comment]
I have the issue as well on 2.17.

**Comment by ram33** [comment]
I was facing the same issue. Initialising parent.nodes to an empty array when no children fixed the issue.
