### ISSUE TITLE
Getting a "Uncaught TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by mwalter-healthagen** [angular-ui-tree/angular-ui-tree#724]
I was getting the same issue as #39, as it turns out that i cannot use the keyword of 'children' in my tree structure, when i changed it to 'nodes' it worked fine (shrug). This should be documented more clearly (if i missed it sorry! :) )
This does not work without throwing "Cannot read property '0' of undefined"
  `{
	"name" : "level1",
	"children" : [{
			"name" : "level2",
			"children" : [{
					"name" : "level3",
					"children" : [{
							"name" : "level4",
							"children" : [
							]
						}
					]
				}
			]
		}
	]
}`

This does
`{
	"name" : "level1",
	"nodes" : [{
			"name" : "level2",
			"nodes" : [{
					"name" : "level3",
					"nodes" : [{
							"name" : "level4",
							"nodes" : [
							]
						}
					]
				}
			]
		}
	]
}
`
Hope this helps somebody!

**Comment by Purewebdesign** [comment]
You can use children, i do it, but if u used an example you found on the internet you have to change the child `<ol>` inside `<script type="text/ng-template" id="nodes_renderer.html">` something like this 

```
<ol ui-tree-nodes="" ng-model="node.nodes">
    <li ng-repeat="node in node.nodes" ui-tree-node ng-include="'nodes_renderer.html'">
    </li>
</ol>
```

to this (watch the changes i have made in ng-model and ng-repeat)

```
<ol ui-tree-nodes="" ng-model="child.children">
    <li ng-repeat="child in child.children" ui-tree-node ng-include="'nodes_renderer.html'">
    </li>
</ol>
```

**Comment by mwalter-healthagen** [comment]
Huh, I had exactly what you just wrote in the line above and got the error... Maybe I overlook something else. Thanks for the note @Purewebdesign, ill give it a go!

**Comment by jacobscarter** [comment]
Closing because @Purewebdesign appears to have provided a solution, please re-open if this is still a problem
