### ISSUE TITLE
createDocumentFragment error on clicking a node

### ISSUE THREAD

**Issue by salmanasiddiqui** [angular-ui-tree/angular-ui-tree#746]
> TypeError: Cannot read property 'createDocumentFragment' of null
>     at Function.n.extend.buildFragment (jquery.js:5087)
>     at n.fn.extend.domManip (jquery.js:5387)
>     at n.fn.extend.append (jquery.js:5218)
>     at dragStart (angular-ui-tree.js:730)
>     at dragStartEvent (angular-ui-tree.js:1044)
>     at angular-ui-tree.js:1084
>     at angular.js:16223
>     at e (angular.js:4905)
>     at angular.js:5285

Occurs on clicking a node.

The setup is as basic as it can be:
1) an array containing data
2) unlimited nesting html
3) click on any node

no callbacks or functions or anything defined.

**Comment by salmanasiddiqui** [comment]
Just found that the issue is $rootElement.append only works if ng-app element is defined. But I am manually bootstrapping the app hence $rootElement.append is not working for me. 
angular-hotkeys faced the same issue, they fixed it by using $document[0].body when $rootElement[0] is document.
https://github.com/chieffancypants/angular-hotkeys/issues/8

**Comment by PinkaminaDianePie** [comment]
i was got same issue and resolved it by bootstrapping not on ```document```, but on ```body```
```javascript
angular.bootstrap(document.getElementsByTagName("body")[0], dependentModulesNames);
```

**Comment by ernestopye** [comment]
Thanks @PinkaminaDianePie - this solved it for me as well. The problem appears to be when updating past 2.9.0. Going from 2.10.0 causes this to start happening. I'm on 2.15.0 now and it seems to work fine again after making this change.

**Comment by jacobscarter** [comment]
This should be fixed because instead of rootElement.append we are now finding body element and appending.
