### ISSUE TITLE
Access controller scope from $callbacks method

### ISSUE THREAD

**Issue by blackat** [angular-ui-tree/angular-ui-tree#750]
Hi,
I have defined the callbacks in this way
```javascript
 vm.treeOptions = {
        accept: accept,
        dropped: dropped,
        beforeDrop: beforeDrop
 };
```
and for each one of them I have defined a `function` further in the code.
I need to access one or more variables defined as ``vm.var1` for instance from the `accept`, is there a simple way to do?

Thanks a lot for the attention.

**Comment by Purewebdesign** [comment]
Put these properties (variables as you like to call them) inside of your `$scope/$rootScope`? Then you've made them global to your document ($scope) or your entire app ($rootScope)

**Comment by jacobscarter** [comment]
Looks like the solution is provided by @Purewebdesign
