### ISSUE TITLE
Edit nodes?

### ISSUE THREAD

**Issue by mbeauchamp7** [angular-ui-tree/angular-ui-tree#753]
Is there a way to edit a node?

**Comment by Exlord** [comment]
??? The nodes are binded to the model ...  edit the model and the node will be updated ...

**Comment by mbeauchamp7** [comment]
Sorry if I wasn't clear. I ment inline editing. I guess I could make an input appear when I select a node. In the demo, there isn't seem to be to do this. Maybe I'm wrong...

**Comment by jacobscarter** [comment]
Closing for lack of detail and because your questions seems to be about personal preference on UI/UX not a question about angular-ui-tree functionality
