### ISSUE TITLE
Can this be used with angular 1.5

### ISSUE THREAD

**Issue by AlexKhymenko** [angular-ui-tree/angular-ui-tree#756]
Can this be used with angular 1.5?
if yes Please update dependencies. :-)
Thank you.

**Comment by tystol** [comment]
+1.
We're using it with 1.5 no problems, but the bower warning is annoying.

**Comment by derek-adair** [comment]
How do you avoid downloading angular 1.4? is ther ea way to ingore all dependencies for a given thing?

**Comment by StefanCodes** [comment]
ui-tree 2.16 has been released that explicitly lists Angular 1.5 as a dependency.
