### ISSUE TITLE
Leading node numbers

### ISSUE THREAD

**Issue by nicolasr75** [angular-ui-tree/angular-ui-tree#757]
I feel somewhat dumb to ask this but I included ui-tree in my code and I always have leading node numbers in front of my nodes like 
1. First node
2. Second node
Where does this numbering come from and how do I remove it? As far as I recognize, I did only copy example code into my app with slight modifications. Looking at the html with developer tools (F12) the numbers do not seem to belong to the nodes but I have no idea how to remove them. My html looks like this:

```
<div ui-tree drag-enabled="false">
	<ol ui-tree-nodes="" ng-model="dataSources">                    
		<li ng-repeat="item in dataSources" ui-tree-node="" 
			ng-include="'dataSourcesRenderer.html'">
		</li>
	</ol>
</div>

<script id="dataSourcesRenderer.html" type="text/ng-template">
        
    <div ui-tree-handle class="tree-node tree-node-content"> 
     <a class="btn btn-success btn-xs" data-nodrag ng-click="toggle(this)">
		<span class="glyphicon" 
			ng-class="{ 
			   'glyphicon-chevron-right': collapsed, 
			   'glyphicon-chevron-down': !collapsed 
			}">
		</span></a> 
		{{item.displayName}}       
	</div> 
	
	<ol ui-tree-nodes="" ng-model="item.items" ng-class="{hidden: collapsed}"> 
		<li ng-repeat="item in item.items" ui-tree-node ng-include="'dataSourcesRenderer.html'"> 
		</li> 
	</ol> 

</script>
```

**Comment by nicolasr75** [comment]
Ok, it was dumb! It was the default numbering of the ol-tag which was active because the ui-tree stylesheet was not correctly included.

**Comment by cherrie12** [comment]
I met this issue also. And how do you solve this problem?

**Comment by nicolasr75** [comment]
Sorry but I don't work with this component anymore. But afair the stylesheet was not included. The ui-tree stylesheet correctly sets the style of the ol-tags to not show numbers, you can check that in the file.
