### ISSUE TITLE
Angular 2 and future

### ISSUE THREAD

**Issue by nicklasb** [angular-ui-tree/angular-ui-tree#765]
Hi everybody,

So I have been lurking this project for a while, and I have been worried about the lack of commits and progress. I think that one could see this in two ways, as a dying project or an opportunity.

There is this real momentum behind wanting to move stuff to Angular 2, and this project, which actually only have Angular as its dependency, seems like a prime candidate to migrate to Angular 2/Typescript.

A fork could also be a natural transferral of control of the project, as the current maintainer doesn't seem to have much time, a A2 fork/rewrite could be a new beginning. 

Perhaps one could also make some core part of it vanilla ES6, so that the base functionality of the treeview could be reused in a react-ui-tree if anyone should be so inclined.

**Comment by ali-habibzadeh** [comment]
I really hope this doesn't get killed. It's packed with good functionality. would be a shame to see it die.

**Comment by nicklasb** [comment]
I don't think that it will be actively killed. Not if the community pulls together.

**Comment by derek-adair** [comment]
Personally, I have zero interest in angular 2 at the given moment and even foreseeable future.  I'm entirely on board for contributing towards the Angular 1 version of this project tho.  I wonder how supporting both angular 1/2 will look like?

**Comment by nicklasb** [comment]
The nicest solution, IMO, would be to treat them as if they were different
frameworks.

That is, breaking out a common vanilla ES6 core and then use that as a
module in A1.x/js and A2/typescript variants.

That way, one could get the most advantages from both.

Another upside with that would be that is would be easy to port the concept
to other frameworks, for example react-ui-tree or whatever.

**Comment by derek-adair** [comment]
Right, so vanilla ui-tree that has implementations in both angular1/2 + other frameworks in the future?

Are there any other projects out there that are structured this way?

**Comment by StefanCodes** [comment]
I've been spending my development time in Angular 2 lately and have been giving this some thought, too. ng2 is pretty dramatically different - especially in the recommended ways of implementing UI controls like this one.

I don't see any practical way to link this project with an ng2 equivalent, aside from, perhaps, the developers interested in working on it. It's certainly practical to use this control inside an ng2 app (props to the Angular team for putting a lot of care into that).

If anyone's interested in starting an ng2 control (angular2-ui-tree or whatever) I'd be very supportive of that. Personally, I'm in a position where I'm working on new code in ng2, but still have some stable ng1 legacy code running ui-tree. Someday I'd like to refactor my legacy application to be entirely in ng2, but that's a big undertaking.

I think ui-tree in Angular 1 has a long life ahead of it.

(But we need more active contributors!)

**Comment by derek-adair** [comment]
Crazy idea:

Convert to plain Ecmascript?

This is a really solid base tree-view implementation.  Loving it the more and more i really dig down deep.  A lot of, if not all of this code can be re-used and/or translated to a vanilla ES6 module.  I *believe* this would make it compatible w/ Angular2 by default? but i've not really played around w/ that yet.

I'm bringing this up because, for a number of reasons, I want to get away from Angular1 ASAP (tl;dir; feeling very uneasy and pissed off at how the angular 1 > 2 upgrade is going) - and this component is(was?) going to be a central piece to my current work efforts.

**Comment by nicklasb** [comment]
I would like to report that it is possible to combine angular-ui-tree and Angular 2 components using ngUpgrade.
It is an admin interface for a framework I am creating(aren't we all) in a hybrid Angular 1/Angular 2 environment.

It is written in Typescript, uses SystemJS/JSPM and has a plugin structure, so its technically pretty advanced and perhaps it is not the most simple example.
But its there, a simpler example should not be too hard to extract from it at some point.
Actually running the system and viewing the content currently takes some effort, so you have to take my word for it that it works. :-)

The code resides here:
https://github.com/OptimalBPM/of-admin/tree/master/ui

**Comment by nicklasb** [comment]
@derek-adair A completely plain ES6 variant is, while possible, not perhaps something that would be useful for at least me, I would like to have the framework integration.

**Comment by jacobscarter** [comment]
Linked to #475 

Are there any volunteers to help with creating an Angular 2 version of this? I can start a repo with some ground work laid out. We can always do a lot of copy and paste I would prefer to re-write it to take advantage of performance increase with can achieve doing things with TypeScript and the "Angular 2 way"

@StefanCodes or @Voles if you make the repo under angular-ui-tree I can commit some base code to get us started for our Angular2 version.

**Comment by nicklasb** [comment]
@jacobscarter Well, at least I am interested. Så please create such a repo. 
I agree on rewriting. On the other hand, that should not take a huge effort, the solutions are there, so I suppose that would not be an insurmountable problem.

**Comment by StefanCodes** [comment]
I would be interested in this as well. My professional work is largely Angular2 now so it would make a lot more sense for me to focus on that aspect.

I'm also quite concerned about our performance issues in ui-tree with large (500+) item trees. I'm likely going to need a tree than can handle several thousand nodes and ng2 is probably better-suited to the task.

I've only barely glanced at how a fresh start in ng2 might work. A dependency on another package like https://github.com/CoderAjay/ng2Draggable might be a time saver, provided it doesn't limit us.

**Comment by Voles** [comment]
If someone is interested in taking the lead for the move to NG2, I'd like to help with the reviews, development process etc. I will probably be working with NG2 at the end of this year.

**Comment by jacobscarter** [comment]
@Voles @StefanCodes I dont have enough privileges to create the angular2-ui-tree repo, can one of you create it please and I can commit the ground work for it.  While you're in there can you delete the other two repos that aren't used

**Comment by Voles** [comment]
I've removed the deprecated website and bower repositories and created `angular2-ui-tree`.
See https://github.com/angular-ui-tree/angular2-ui-tree

@StefanCodes ng2Draggable looks like a nice start for the drag and drop logic / syntax!

@jacobscarter can you take the lead on the initial setup in a PR? I think it will be important to gather initial feedback from as many eyes as possible.

Let the fun begin! 🎈

**Comment by shahpranaf** [comment]
Hi All,

@Voles I would like to work on this project. I'll do the initial setup.

Request you to change the heading of Angular UI tree(this project) to Angularjs UI tree.


Thanks

**Comment by kikkiraj** [comment]
@voles is AG2 still alive???
