### ISSUE TITLE
Open a node when you hover the other node

### ISSUE THREAD

**Issue by krloscosta34** [angular-ui-tree/angular-ui-tree#768]
I saw the project history and this was already implemented at the issue #210 but the implementation is lost.

Can someone commit again?

**Comment by derek-adair** [comment]
Duplicate.... #210

**Comment by derek-adair** [comment]
Which was reverted at some point unfortunately.

**Comment by derek-adair** [comment]
I know its closed but we can re-open it once we get more active contributors (hoping for commit access soon).

**Comment by jacobscarter** [comment]
expandOnHover is in the most current release.
