### ISSUE TITLE
Drop inside a empty parent

### ISSUE THREAD

**Issue by nijeeshvayalassery** [angular-ui-tree/angular-ui-tree#771]
Thanks for this awesome module.
Issue i am facing is when dropping into a node which has no children's, its very hard to get the node dropped in side node. The solutions i have found in this issue threads are to put an null array if node is empty. I have tried that ,but still there is difficulty in placing the node inside parent. It would be very hep full if you can help on this.

Thanks in advance.

**Comment by derek-adair** [comment]
Have you tried over-riding the drop-zones CSS?

**Comment by nijeeshvayalassery** [comment]
Its fixed. the issue was, by default i am collapsing all the nodes. so the node without children also gets collapsed. what i did is, in drag move i expanded the children nodes of the current parent.

**Comment by derek-adair** [comment]
Hm, that's clever.

this seems like  a symtom of another bug.  i think there is something about expanding a collapsed node on drag or something hanging around here, you may want to check it out.
