### ISSUE TITLE
The situation of the project is untenable

### ISSUE THREAD

**Issue by nicklasb** [angular-ui-tree/angular-ui-tree#773]
The last commit to the project was now 5 months ago. This is untenable, it is obvious that the project maintainer no longer have time for the project. 

This is the way it is with open source projects, the people behind them come and go. 
I don't know why a project with almost 2000 stars on github end up unmaintained. 
It may be that @Voles didn't feel the proper involvement from the users. 
And, well, to his defence, I can't say I see a myriad of PRs.

I am not sure how many more but @Voles  are maintaining this project, but I do know that if nothing is done soon, it will go away.
And I don't think that is a good thing. @Voles  have created a great component here, and it serves a purpose.

People needs to commit to this project for it to work.

Ironically, I myself is involved in several other FOSS projects, so I do not have the time.
But some of you must. Please discuss this here.

**Comment by derek-adair** [comment]
Glad to see this post here, i just noticed this as well.  I am more than willing to contribute what I can... this component is easily the best tree-view in angular from my best estimate.  5 months is a very long time to be gone.  Looking at @voles contributions it looks like he's kicking ass on a private project for the past 5 months.  I've reached out to him in an effort to see if we can be more involved with the maintenance of this project.

**Comment by derek-adair** [comment]
For what its worth i had some immediate needs to build this project w/ angular 1.5 via bower so I forked, and registered a new bowerpackage... .angular-ui-tree-redux.  Let me know if you think anything should be pulled in and we can make a release.

**Comment by StefanCodes** [comment]
I agree, the project needs help. I have committer privileges but very little time to even think about this project lately. I'm setting aside some time on Sunday to merge the existing PRs that are in good shape, but I don't expect to be able to give much ongoing attention to the project.

Fundamentally we need a few more active contributors. Perhaps some of the regular commenters in the issues are willing to step forward? Regardless, I haven't had any contact with @Voles, so we'll have to wait until he chimes in before anyone else can be granted permissions to the project.

**Comment by nicklasb** [comment]
Well, if you have commit rights, that is a start.

**Comment by derek-adair** [comment]
woot.  looks like my redux release can be deleted shortly.  (still need it for now until youc an merge my request or else i'm dead in the water).

**Comment by derek-adair** [comment]
If you can give me commit rights I can help organize the issues on my down time.  There are about 250 open right now that need attention.  Right now i'm gonna just go through what I can and solicit pull requests for those that are relevant.

**Comment by StefanCodes** [comment]
I only have commit rights to the repo - unfortunately I don't have any rights to add or remove people from the project. We're going to have to wait for @Voles to return before we can add anybody new.

I'm happy to merge PRs and keep bumping release numbers. My biggest problem is that I spend little time working in Angular 1 and with ui-tree, so I spend far too much time getting my head back into ui-tree before I can do much (which sucks when I only had an hour or two to spend in the first place).

Until we've got some new people added, anyone willing to review PRs and provide feedback as to their suitability would be a huge help.

**Comment by derek-adair** [comment]
understood, definiltey trying to figure out whatever magic incantation we need to get @voles back :p hahah.  Thanks for how responsive you've been so far.  

I'll see what I can do about reviewing some PRs and actually fixing some behaviors that I am needing personally which I've filed under #777 and #778. If/when he gets back I can hopefully be a lot more involved in the management of this project as i've already made the decision to go with this on a project i'm using.

we shall see!

cheers

**Comment by nicklasb** [comment]
Incantation? I'd rather try sufficiently advanced technology. :-)

Cool!

**Comment by Voles** [comment]
Hey all! First of all, sorry for the late reply.
I've indeed spent more time on other projects. I have been working on a React and Ember applications, so it wasn't obvious for me to work on this Angular module.

 I'm definitely willing to put some more time in Angular UI Tree again! However, I don't want to give just anyone push rights from the start. There's plenty of other work to do which would also help a lot:
- going through issues and trying to resolve them (or close if irrelevant)
- review PR's
- setup contribution guidelines so we have some sort of formal process (which hopefully increases the quality of PR's)
- automate the release process (generate changelog, publish to NPM, Bower and on GitHub)
- cleaning up the README / website / documentation
- add E2E-tests

So there's enough challenges to tackle! Guess if there's more interactivity coming from other people (apart from creating issues), I'll also be more motivated to keep working on UI Tree!
