### ISSUE TITLE
Need to push tag for bower release

### ISSUE THREAD

**Issue by derek-adair** [angular-ui-tree/angular-ui-tree#779]
In order for bower to register a new release you need to push the tagged version up to github.  Let me know if this is unclear or you need any help with this.

Also if you somehow got me write access I can take over that aspect.... please ;)

**Comment by derek-adair** [comment]
@Voles plz... sir...

**Comment by StefanCodes** [comment]
Whoops, forgot to check the 'push tags' box! That should be live now.

**Comment by derek-adair** [comment]
Looks good
