### ISSUE TITLE
expandOnHover attribute considers only boolean value.

### ISSUE THREAD

**Issue by pkatta** [angular-ui-tree/angular-ui-tree#793]
expandOnHover attribute should be consider boolean and numeric value.
Boolean : Will expand each node when user drags on node.
Numeric : Will expand the node only when the user drags node and hover node to particular time.

**Comment by jacobscarter** [comment]
@pkatta Are you suggesting we add a customizable delay on the expandOnHover?

**Comment by pkatta** [comment]
@jacobscarter : Yes.

**Comment by pkatta** [comment]
@jacobscarter : Please check my PR for same.
https://github.com/angular-ui-tree/angular-ui-tree/pull/792

**Comment by jacobscarter** [comment]
PR was merged, closing ticket
