### ISSUE TITLE
Error on pressing button esc

### ISSUE THREAD

**Issue by c0mradeuc** [angular-ui-tree/angular-ui-tree#799]
![screenshot_37](https://cloud.githubusercontent.com/assets/16196167/17333915/502fcc76-58a2-11e6-946b-80dde81321fe.png)

In chrome when i press esc a error is logged.

**Comment by jacobscarter** [comment]
Fixed in PR https://github.com/angular-ui-tree/angular-ui-tree/pull/807

**Comment by Voles** [comment]
#807 has been merged.
