### ISSUE TITLE
Error: ngRepeat:dupes Duplicate Key in Repeater 

### ISSUE THREAD

**Issue by nifft** [angular-ui-tree/angular-ui-tree#802]
I have set up the following tree. 
```
<div ui-tree="treeOptions" id="tree-root" data-drag-delay="1000"
        data-max-depth="3">
          <ol ui-tree-nodes ng-model="data">
            <li ng-repeat="node in data" ui-tree-node
            ng-include="'nodes_renderer.html'"></li>
          </ol>
        </div>
```
The model is initially empty.

```
$scope.data = [];
```

Then I populate the tree and get a model like the following.

`
[{"id":"c82561ec215a6e31807ceedf3b3bd25e","title":"n1","description":"d1","nodes":[{"id":"a6bbc91ae73dd21c0533f735470a9cd0","title":"n2","nodes":[],"$$hashKey":"object:58"}],"$$hashKey":"object:43"},{"id":"4443aee183b279f76a95c13c7f5bca0d","title":"n3","nodes":[],"$$hashKey":"object:72"}]
`

Ids are generated using md5 hashes. Then I use **angular's toJson** to get rid of $$hashKeys. Then I save this model using rest. 

Now comes the weird part. If I attach this new model to the scope's data variable when my Ionic app's view loads, then the tree renders just fine. But when I use REST/WebSockets, **to reassign the value of the scope variable** ($scope.data), then I get **Error: ngRepeat:dupes Duplicate Key in Repeater** .

Please help.

**Comment by jacobscarter** [comment]
@nifft it is hard to say without seeing nodes_renderer.html but this error is almost always fixed by adding `track by`.  For example:

`<div ng-repeat="row in data track by $index">`

**Comment by jacobscarter** [comment]
I will close this, please re-open if it is still an issue or you have further questions

**Comment by wggley** [comment]
+1 
track by $index doesn't work

**Comment by ruth8** [comment]
+1 
same issue.
