### ISSUE TITLE
Horizontal Trees?

### ISSUE THREAD

**Issue by jacobscarter** [angular-ui-tree/angular-ui-tree#803]
I am getting some poor performance from angular-ui-tree and unexpected behavior, due to the amount of PRs and Issues open I decided to fork and use my own repo.

While cleaning up some code i see what looks like leftovers from when a horizontal tree was supported, but I can't find any documentation for it.

Is this something that was removed or something that is currently being added?

**Comment by jacobscarter** [comment]
On this note there were two major problems that were blockers for me with angular-ui-tree, the first was not being able to drag a node from one tree to another that were side by side, this was because unless it broke the hard coded threshold of 30px it would not register as a vertical movement and therefor not hit the logic to move the node from one tree to another.

The second problem was a major (around 200ms) delay when starting to drag a node and when the dragElement would appear in the UI.  I tracked this down to the way the dragDelay function is written.  

As a quick fix i removed all horizontal tree logic because it doesn't appear to be supported anymore and I added an if check that skips the dragDelay function all together is no drag delay was specified by the user.

Let me know if any of that is worth a PR to you.

**Comment by Voles** [comment]
@jacobscarter we don't intentionally support horizontal trees. I can imagine some people do / will want to use it. In that case it should be explicitly documented + a sample added to our demo page.

Thanks for investigating and sharing your work with us!

**Comment by Voles** [comment]
Closing as this is being solved with #806 and #810

**Comment by StefanCodes** [comment]
I vaguely recall that there was an additional horizontal tree-based demo on the old demo page (the one under @JimLiu's GitHub account). That appeared to be long-obsolete before I started using ui-tree.

There may be some misleading comments or unused logic lingering in the code base from that functionality - I vaguely recall seeing unexpected code/comments when I've been working on other stuff.

In all likelihood, those stray bits of code (if they exist) should be removed, but I don't think we should go looking for them in case we cause a bunch of subtle regressions.
