### ISSUE TITLE
Contributor review/deployment process

### ISSUE THREAD

**Issue by StefanCodes** [angular-ui-tree/angular-ui-tree#809]
There's a handful of steps involved in processing a PR and deploying a new release of angular-ui-tree. I've briefly recorded the steps I followed in processing the last few PRs.

What I'd like from this ticket is for us ( @Voles  @jacobscarter) to reach a consensus on a process that works for everybody, and then get this documentation somewhere we'll find it (like the readme).

## Accepting PRs:

- Manually review PR in the Files Changed tab of the GitHub PR section
- Ensure Travis build passing
- Review coveralls and codacy reports. A fail does not necessarily mean a PR should be rejected, but it is a red flag that you should take a close look at the report.
- Merge the PR. If the PR is simple and good as-is you can merge it using GitHub's web UI. If the PR needs some amending, or you want to test the changes, perform a command line merge (the 'commandline instructions' link gives the commands).
- Test the PR locally and run the tests (gulp test and gulp test:e2e)
- Make any additional changes you need (update README, update example site, etc)
- Push the changes

(rinse and repeat for each PR)

## To create a release:
- Re-run the tests (gulp test and gulp test:e2e)
- Consider if any new functionality should be represented on the demo page
- Update CHANGELOG.md with release notes for the changes in the this release
- Update version string in source/main.js
- Run gulp build and commit, this time including the new dist files.
- Tag the commit as a new release (like v2.18.0)
- Push all the changes
- Update the website by running gulp website (runs the ghpages plugin)

**Comment by jacobscarter** [comment]
Bullet to add to "To Create A Release" section 

* Publish to npm with `npm publish ./`

All necessary people will need to be added to the npm account on http://npmjs.org

Command line details for making sure the bower package is updated:

```
# commit your changes
git commit -am "Made some awesome new changes, now its even awesomer"

# tag the commit
git tag -a v0.0.2 -m "Release version 0.0.2"

# push to GitHub
git push origin master --tags
```

We should put this in a CONTRIBUTING.md file

Also I notices in the angular-ui-tree account there is a repo called bower-angular-ui-tree, maybe we should delete that repo to avoid any confusion.

Bullet to add to "Accepting PRs" section

* Make sure no dist/ files are in the PR.

Everything else looks great! That is all I have for now, let me know what you think.

**Comment by Voles** [comment]
@StefanCodes this is perfect. I've created a PR with the sections you've suggested + a section on how to submit a PR.

@jacobscarter great idea to create a CONTRIBUTING.md file. I've looked into the `bower-angular-ui-tree` repository and it seems like it isn't used anyhow. @StefanCodes do you too agree we can remove it? All files needed for Bower are inside our main `angular-ui-tree` repository.

These steps are a great to streamline our process. However, I think much can be automated still (eg. performing the release process using a bash script). I'll look into that part later.

**Comment by Voles** [comment]
Another thing we can add is a template for new issues. See https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by jacobscarter** [comment]
@Voles can we close this now that your docs were merged in?
