### ISSUE TITLE
Regression in moving items horizontally (up/down in depth) with v2.18.0

### ISSUE THREAD

**Issue by Tibfib** [angular-ui-tree/angular-ui-tree#813]
I can't get any items to move horizontally properly... However, when I download v2.17 and run it locally, I can move horizontally without a problem.

To replicate, just compare the example site from v2.18 with v2.17.... 

I'm using Chrome v53.

Thanks for the library!

**Comment by jacobscarter** [comment]
Hi @Tibfib I cannot duplicate the issue, if I pull down the latest and run `gulp serve` all horizontal movement works as expected.

The only thing I can think of would be the roll back we did earlier, I will push a new version "2.19.0" which should take care of any problems with 2.18.0 referring to the "wrong" files.

Please pull down 2.19.0 and let me know if you are still experiencing the problem.

Our Github Pages is up to date with 2.19.0 and horizontal movement appears to be working there as well.

http://angular-ui-tree.github.io/angular-ui-tree/#/basic-example

**Comment by Tibfib** [comment]
`2.19` works for me! The website also works again.

Thanks! As far as I'm concerned, this can be closed.
