### ISSUE TITLE
Directive conflict with Angular Material

### ISSUE THREAD

**Issue by sylouuu** [angular-ui-tree/angular-ui-tree#838]
Hello,

I'm new here and I wanted to use this plugin to provide sorting in my Angular Material table.

My current code looks like this:

```html
<table md-table>
    <thead md-head>
        <tr md-row>
            ...
        </tr>
    </thead>
    <tbody md-body>
        ...
```

I've installed the plugin and started tu update my markup like your "Table example" in the demo page like:

```html
<table md-table ui-tree>
    <thead md-head>
        <tr md-row>
            ...
        </tr>
    </thead>
    <tbody md-body ui-tree-nodes>
        ...
```

When I try it I get [this error](https://docs.angularjs.org/error/$compile/multidir?p0=mdTable&p1=%20(module:%20md.data.table)&p2=uiTree&p3=&p4=new%2Fisolated%20scope&p5=%3Ctable%20md-table%3D%22%22%20ui-tree%3D%22%22%20class%3D%22md-table%22%3E).

```
Multiple directives [mdTable (module: md.data.table), uiTree] asking for new/isolated scope on: <table md-table="" ui-tree="" class="md-table">
```

What should I do about this?

- OSX El Capitan
- Chrome 53
- Angular 1.5.8
- Angular Material 1.1.0-rc.5
- Angular UI Tree 2.22.1

Bests

**Comment by sylouuu** [comment]
Any advice @rintaun ?

**Comment by jacobscarter** [comment]
This is caused because both ui-tree and ng-material want isolated scope and you cannot have two directives asking for isolated scope on the same element.  The only solution to this would be for one of those two directives to no longer require isolated scope. Unfortunately there is not a quick fix for that.

**Comment by jacobscarter** [comment]
I will leave this open to see if @Voles or @StefanCodes thinks we should attempt to re-write ui-tree to not use isolated scope, I vote against it, at least in the near future, what are your two's thoughts?

**Comment by rintaun** [comment]
I'm not sure why I was tagged in this, but whatever.

This issue should be closed. It isn't really feasible to to rewrite ui-tree to not use isolate scope. On the other hand, after briefly looking into it, the md-data-table module (I assume you're using [daniel-nagy/md-data-table](https://github.com/daniel-nagy/md-data-table) -- correct me if I'm wrong) doesn't seem to actually be _using_ the isolate scope that it needs, so changing that would likely be incomparably easier.

Of course, there's a much easier solution here: just wrap the entire thing in a `<div>` and use that for the ui-tree container instead. It looks like md-body doesn't request isolate scope, so there shouldn't be any conflict with ui-tree-nodes, and afaik, that should work just fine.

**Comment by sylouuu** [comment]
Thanks for your answers. I just removed md-table and it works well.

I noticed something, if you put `<button ui-tree-handle>` the drag doesn't work.
I had to wrap the button with `<div ui-tree-handle>`.

Bests
