### ISSUE TITLE
data-expand-on-hover seems no use.

### ISSUE THREAD

**Issue by tinybright** [angular-ui-tree/angular-ui-tree#839]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
data-expand-on-hover seems no use.

**What is the expected behavior?**
the node to expand (if it contains child nodes and was collapsed) when dragging a node over it

**Comment by Manveroo** [comment]
Hi tinybright

Did you use a version >= 2.18?
The feature was implemented there.
See [changelog](https://github.com/angular-ui-tree/angular-ui-tree/blob/master/CHANGELOG.md#2180)

Kind regards

**Comment by Manveroo** [comment]
Thanks btw. I wondered myself why it was not working :-)
