### ISSUE TITLE
How to open popup

### ISSUE THREAD

**Issue by BharatGK** [angular-ui-tree/angular-ui-tree#840]
Hello all,

As soon as i drop my source to destination, i want to open pop up box or may be alert box then how i can do that, where to call alert or popup box function.

Please put  your suggetion.

Thanks!

**Comment by StefanCodes** [comment]
It sounds like this demo does what you're asking: http://angular-ui-tree.github.io/angular-ui-tree/#/drop-confirmation.
Please reopen this issue or ask in chat if this doesn't solve your problem.
