### ISSUE TITLE
How to open popup on success of drop

### ISSUE THREAD

**Issue by BharatGK** [angular-ui-tree/angular-ui-tree#842]
Hello all,

How i can open model pop-up on success of drop from source to destination.
Now, drop confirmation shows model as soon as click on it, i want to open model on success of drop from source to destination.

Put your suggestion and keep building
thanks.!

**Comment by jacobscarter** [comment]
See answer to your previous question regarding [callback events](https://github.com/angular-ui-tree/angular-ui-tree#droppedevent).
