### ISSUE TITLE
Prevent root node from being draggable, but allow draggable children

### ISSUE THREAD

**Issue by dclarke83** [angular-ui-tree/angular-ui-tree#844]
I had this issue and it was suggested on Gitter that I share how I worked around this.

![image](https://cloud.githubusercontent.com/assets/18419752/19125988/0d843026-8b31-11e6-9f30-d5a41cfd897b.png)

The easiest thing to do would be to just not show the root node if I don't want people to drag it - but then I would not be able to add children to it via the same UI as I have for other child nodes (the buttons on the right).

Adding "data-nodrag" to the root level `<li>` or `<ol>` makes the entire tree not draggable (when I only want the root to not be draggable).

The solution is (using the example `nodes_renderer.html` template) to make the `<div>` not draggable instead by adding this to the `<div>` with the `ui-tree-handle`:

`ng-attr-data-nodrag="{{node.ilevel == '3' || undefined}}"`

(where node.ilevel == '3' indicates that it is the root node from my data)

**Comment by konstantinkrassmann** [comment]
Hi, Thank you for the tip here. 

I tried that out, but it doesnt seem to work with my script: 

``` html 
<script type="text/ng-template" id="nodes_renderer.html">
                        <div ui-tree-handle
                             class="tree-node tree-node-content angular-ui-tree-handle"
                             data-ng-attr-data-nodrag="{{ node.type=='customer' || node.type=='building'">
                           
                            {{node.name}}
                        </div>
                        <ol ui-tree-nodes=""
                            data-ng-model="node.children">
                            <li
                                data-ng-repeat="node in node.children"
                                ui-tree-node
                                ng-include="'nodes_renderer.html'">
                            </li>
                        </ol>
                    </script>

                    <div ui-tree class="angular-ui-tree">
                        <ol ui-tree-nodes="" data-ng-model="keysCtrl.oKeyTreeStructure.client.children"
                            class="angular-ui-tree-nodes">
                            <li ng-repeat="node in keysCtrl.oKeyTreeStructure.client.children"
                                ui-tree-node ng-include="'nodes_renderer.html'"
                                data-nodrag
                                class="angular-ui-tree-node"></li>
                        </ol>
                    </div>
```

**Comment by konstantinkrassmann** [comment]
👍  Thank you, that was really helpful!
