### ISSUE TITLE
Node sort works in tree view using filter but underlying model not sorted 

### ISSUE THREAD

**Issue by vtmoren** [angular-ui-tree/angular-ui-tree#845]
I want to use a orderBy filter to order my nodes:
``` 
<ol ui-tree-nodes="" ng-model="item.children" ng-class="{hidden: collapsed}">
            <li ng-repeat="item in item.children | orderBy: 'value' track by $index" ui-tree-node data-collapsed="true" ng-click="(!item.children && !item.compatible) ? '' : setSelectedStatistic(this)"
                ng-include="'item_renderer.html'" ng-style="(!item.children && !item.compatible) ? {'color' : 'rgb(180, 180, 180)', 'pointer-events' : 'none'} : ''">
            </li>
        </ol>
```
In the view the nodes are sorted but the ng-model seems to be in the same order (so the setSelectedStatistic(this) method does not return the correct node...any ideas? I thought the filter would affect the model as well?

**Comment by jacobscarter** [comment]
The solution to this is to not sort in the view, sort using a method in your controller. e.g.

```
$scope.item.children = $filter('orderBy')($scope.item.children, 'value');
```

**Comment by vtmoren** [comment]
Agreed.  I ended up filtering the object beforehand and the issue was fixed.  Thanks.
