### ISSUE TITLE
Specify what property is displayed while a node is dragged

### ISSUE THREAD

**Issue by sylouuu** [angular-ui-tree/angular-ui-tree#850]
Hello,

Sorry about this title.

I've performed my searches but didn't find in README and live demos.

Go to http://angular-ui-tree.github.io/angular-ui-tree/#/table-example and drag a node without dropping it.

You will see "node x (remove button)". Is that possible to specify what to show there, like the title only "node x" or any object property?

Bests

**Comment by ivanhuay** [comment]
+1 :cry:

**Comment by sylouuu** [comment]
Adios amigos
