### ISSUE TITLE
webpage freeze when there are too many nodes!!

### ISSUE THREAD

**Issue by IChocolateKapa** [angular-ui-tree/angular-ui-tree#860]
*bug*

when I request a node's children nodes, if there are many, like over 2000,  the webpage just frozen,  and it would last a very long time....... OMG, how can I solve this problem?

**Comment by StefanCodes** [comment]
This is a known performance issue tracked in https://github.com/angular-ui-tree/angular-ui-tree/issues/424

The short answer is that the fundamental way Angular 1 handles watches is a severe problem with the way angular-ui-tree manages node state. As this point no one has come forward with a solution to make this control scalable to hundreds of nodes.
