### ISSUE TITLE
sometimes,when i drag the node,it cannot read property '$$phase' of null.

### ISSUE THREAD

**Issue by smart-dream** [angular-ui-tree/angular-ui-tree#867]
sometimes,when i drag the node ,it will be error.Especially when you drag from a subset to a parent.
TypeError: [Error] Cannot read property '$$phase' of null.

Hope you help me to see,thanks!

**Comment by imccoy** [comment]
I was seeing an issue like this that was caused by an ng-if on my ui-tree-nodes element. Either using an ng-hide instead or moving the ng-if to the ui-tree-node-element resolved the issue for me.

**Comment by Voles** [comment]
Closed with #964
