### ISSUE TITLE
Adding labels to the trees

### ISSUE THREAD

**Issue by wjrivera** [angular-ui-tree/angular-ui-tree#881]
**Do you want to request a *feature* or report a *bug*?**
Is there a way to have labels on the tree?

Included is a picture of what I'm trying to accomplish
![angular-ui](https://cloud.githubusercontent.com/assets/9951818/21730351/6114f952-d41d-11e6-92f9-d0eba2db736c.png)

Thank you

**Comment by Evanion** [comment]
You can add what ever content you want to the nodes .. and you can check if they are a sub item in the 'dropped' event.

**Comment by wjrivera** [comment]
Thank you
