### ISSUE TITLE
Controller 'uiTreeNode' and 'uiTree' cannot be found

### ISSUE THREAD

**Issue by mstamatiadou** [angular-ui-tree/angular-ui-tree#89]
Hi! 

I read the comments on issue #81, got the last update for the code and also updated angularjs to v1.3.0-beta (which I read that doesn't have any issues with your module). 
However, I am still getting the same errors as before: 

Error: [$compile:ctreq] Controller 'uiTreeNode', required by directive 'uiTreeHandle', can't be found!
and
Error: [$compile:ctreq] Controller 'uiTree', required by directive 'uiTreeNodes', can't be found!

Have I missed something? I am struggling to find a solution but I am really new to Angularjs... so, any, any help is appreciated! :) 

Thanks!

**Comment by ekarudianto** [comment]
I faced this issue also thanks @alex88 for the answer !
