### ISSUE TITLE
Dragging cloned node onto empty tree removes the empty tree placeholder

### ISSUE THREAD

**Issue by peter-norton** [angular-ui-tree/angular-ui-tree#908]
![missing_angular-ui-tree-empty_element](https://cloud.githubusercontent.com/assets/5089611/23086035/8a0f2e48-f530-11e6-8e1b-90be5d33b1f7.gif)

To recreate: 

1. go to [Connected Trees Cloning](http://angular-ui-tree.github.io/angular-ui-tree/#/cloning)
2. delete all the nodes in Tree 2
3. try to drag a node from Tree 1 onto Tree 2.

Expected behavior: the `angular-ui-tree-empty` element should stay in place until the node is dropped.

**Comment by Voles** [comment]
@peter-norton thanks for reporting! The fix has been proposed here: #895
Do you have time to help reviewing this PR?

Thanks in advance!

**Comment by peter-norton** [comment]
@Voles Any chance my pull request ([#910](https://github.com/angular-ui-tree/angular-ui-tree/pull/910)) could be merged?

Here's the fix in action (notice that the placeholder doesn't disappear until the node is dropped):
![fixed](https://cloud.githubusercontent.com/assets/5089611/23775352/eccf49a6-04ed-11e7-8ae9-03d1e80c9582.gif)

**Comment by Voles** [comment]
@peter-norton I'm considering to include your work, but I'm not sure if this is really useful. Because you can drop the slide on that area, right? Wouldn't you want a 'drop placeholder' then?

Do you know any other scenarios where people would want this as the default behaviour for the tree component?

**Comment by peter-norton** [comment]
It's really just a stylistic change. It doesn't make sense for the empty tree placeholder to disappear when dragging and hovering over top of it

**Comment by Voles** [comment]
Resolved by #910
