### ISSUE TITLE
not showing tree view

### ISSUE THREAD

**Issue by smohammedyasin** [angular-ui-tree/angular-ui-tree#923]
Hello,

I'm not getting any tree view from treeData.
Please check [http://plnkr.co/edit/3fv3RAA3VgBbVSd58OaT?p=preview](http://plnkr.co/edit/3fv3RAA3VgBbVSd58OaT?p=preview).

did i missed anything?

Appreciate for quick response

**Comment by EmmanuelVictor62** [comment]
@smohammedyasin, what was your solution to this??

**Comment by maanii10** [comment]
@EmmanuelVictor62 i used [PrimeNg Tree](https://primeng.org/tree) and it has many options and customized things.

**Comment by maanii10** [comment]
> @smohammedyasin, what was your solution to this??

check your data, the  json array has to be with same properties
```
 [{
        "id": 1,
        "title": "Products",
        "nodes": [child nodes ....]
      }]

```
