### ISSUE TITLE
Accessing event.dest.nodesScope.$modelValue in dropped callback function

### ISSUE THREAD

**Issue by jamesvn93** [angular-ui-tree/angular-ui-tree#993]
Is it possible to access the event.dest.nodesScope.$modelValue within the dropped callback function?

Within the dropped callback I can console.log this value like this (since console.log is async it waits for the dropped callback to finish):

    $scope.treeOptions = {
        dropped: function (event) {
        var destNodes = event.dest.nodesScope.$modelValue
        console.log(destNodes);

But when I try and use this value to post to my controller where I use the updated list to sort it in my database within the callback, the old list is getting posted and not the updated list after the drop.  

    $scope.treeOptions = {
        dropped: function (event) {
        .............
        var Indata = { 'children': destNodes , 'parent': $scope.parent, 'jobId': $scope.JobId };
        $http.post(sortActivity, Indata).then(function successCallback(response) {
            toastr.success('Data Saved!');
            $scope.data = response.data;
        }, function errorCallback(response) {
            $log.warn(response.data);
        });

It seems I can only access the new list after the dropped callback is successfully executed by storing it in a global variable.  The problem with that is I cannot directly 'sort' my list after a drop has occurred.  I have tried making use of promises and watches to access the new list but it seems its only possible after dropped is executed completely.

If one is able to access event.dest.nodesScope.$modelValue within the dropped callback it would be possible to update the list for sorting purposes at its source be it a database or some other storage method.

I am using AngularJs 1.6.5 and using v2.22.6 of angular-ui-tree

**Comment by ltoshev** [comment]
Hi

yes this suddenly stopped working, recently on our site too. The UI-tree is not updated, so it has to be some of its dependencies that updated and we no longer can take the right value from  event.dest.nodesScope.$modelValue 

Please provide an urgent fix if possible

Using AngularJs 1.5.11 and using v2.22.6 of angular-ui-tree

**Comment by ltoshev** [comment]
Anyone?

**Comment by vs-kiann** [comment]
I am have the same issue here as well ! 
 Using AngularJS 1.4.10 and using v2.22.6 of angular-ui-tree

**Comment by ltoshev** [comment]
I have found a fix: // I commented out the timeouts, so that modelValue collection is updated immediately.

$scope.removeNode = function (node) {
          var index = $scope.$modelValue.indexOf(node.$modelValue);
          if (index > -1) {
            //$timeout(function () {
              $scope.$modelValue.splice(index, 1)[0];
            //});
            return $scope.$treeScope.$callbacks.removed(node);
          }
          return null;
        };

        //Called in apply method of UiTreeHelper.dragInfo.
        $scope.insertNode = function (index, nodeData) {
          //$timeout(function () {
            $scope.$modelValue.splice(index, 0, nodeData);
          //});
        };

And then in my dropped handler:

Like so:

 dropped: (event) => {
                    var page = event.source.nodeScope.$modelValue; // get source value
                    var previous = event.dest.index-1 >= 0 ? event.dest.nodesScope.$modelValue[event.dest.index-1] : null; // now here the collection is allready updated and I can consistently get the previous page from the new collection!
                    ....
                }

This is fix is created by SimpleSite.com team by Lyubomir Toshev

**Comment by jamesvn93** [comment]
@ltoshev commenting out the timeouts for the removeNode and insertNode functions did the trick for me.  Working as intended now, Thanks!

**Comment by ikalafat** [comment]
@jamesvn93 just a quick tip, as I've encountered this issue minutes ago. Unfortunately, I cannot edit original JS files as they are bundled, so i had to come up with another solution. 

In my case, i wrapped my code within "dropped" callback into $timeout, and voila, it works, the $modelValue is updated once $timeout's callback fires.
